### ISSUE TITLE
feat(keychain-azure-kv): complete request handler and endpoints

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cactus#1010]
### Description
As a developer, I want to complete the code to enable the endpoints
get-keychain-entry
set-keychain-entry
delete-keychain-entry (or maybe use set-keychain-entry with tags for deletion)
Also, write tests that use the API client instead of the plugin instance directly.

### Acceptance Criteria
1. Update openapi.json at packages/cactus-plugin-keychain-azure-kv/src/main/json/openapi.json
2. Update the endpoints at packages/cactus-plugin-keychain-azure-kv/src/main/typescript/webservices
3. Update the remote adapter code at packages/cactus-plugin-keychain-azure-kv/src/main/typescript/plugin-keychain-azure-kv-remote-adapter.ts
4. Update the test code at packages/cactus-plugin-keychain-azure-kv/src/test/typescript/integration/plugin-keychain-azure-kv.test.ts

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy @petermetz  @TonyRowntree @travis-payne

**Comment by petermetz** [comment]
cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by Jeff-Ushry** [comment]
Working on it now

**Comment by ty-lazar** [comment]
@petermetz  the cactus-plugin-keychain-azure-kv package doesn't exist - could it be an old name for a package that was since renamed?

**Comment by TonyRowntree** [comment]
> @petermetz the cactus-plugin-keychain-azure-kv package doesn't exist - could it be an old name for a package that was since renamed?

believe this issue is dependent on #991

**Comment by jagpreetsinghsasan** [comment]
@ty-lazar the azure-kv plugin is still in PR, thus not yet visible in the code.
