### ISSUE TITLE
Support Fabric 2.0

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#102]
### Description

Fabric 2.0 has been released very recently.

As a developer I want to be able to work with Fabric 2.0 through BIF so that I'm not stuck on the older 1.x versions of Fabric if I chose to work with BIF.

The assumption here is that Fabric 2.0 being a major release, it contains breaking changes that may need us to have a totally separate connector for it, essentially treating it like a completely separate ledger type.
It is possible that we can just support both 1.x and 2.x with the existing Fabric connector having some changes in it that decide at runtime based on the Fabric version how to act. 

### Acceptance Criteria
1. Evaluate if dedicated connector is necessary or easier/simpler to retrofit 1.x Fabric connector to support both 1.x and 2.x at the same time.
2. Add Fabric 2.0 as a supported example IF it was deemed necessary to have code for it in a dedicated connector.

**Comment by RafaelAPB** [comment]
I am working on this.

**Comment by petermetz** [comment]
Added support for running transactions on both 1.4.x and 2.2.x with https://github.com/hyperledger/cactus/pull/394 
Contract deployments for both are on the way but are covered by a separate issue so closing this one as complete.
