### ISSUE TITLE
docs: node tap --ts flag missing

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1034]
### Description

Make sure the documentation provides up to date example commands for running the tests.

See for more context:
https://github.com/hyperledger/cactus/pull/1029#issuecomment-860971294

### Acceptance Criteria
1. All mentions of  `tap` is updated where applicable.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @kikoncuo @petermetz @arnab-roy @TonyRowntree @travis-payne

**Comment by elenaizaguirre** [comment]
Working on this!
