### ISSUE TITLE
refactor(validator): refactor the config files on Go-Ethereum Validator

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#1039]
**Is your feature request related to a problem? Please describe.**
In the current Cactus codes, the config settings are written in local config files.
However, in the case of maintaining codes on servers such as docker containers, it is desirable to manage the settings under the "/etc/cactus/..." such as the following structure:

- /etc/cactus/validator-<DLT-id>-settings.yaml
  - port
  - logging-dir
  - connectivity-info
    - ip
    - port
    - ...
- /etc/cactus/validator-<DLT-id>-secrets.yaml
  - sign-key
  - auth_credential

**Describe the solution you'd like**
To refactor the configs settings in order to solve the above issues.
This issue is the special case of Issue #1003. After resolving it, I have a plan to refactor other parts according to the above structure.

**Comment by petermetz** [comment]
@takeutak Test message

**Comment by takeutak** [comment]
@petermetz Thanks

**Comment by takeutak** [comment]
@petermetz Sorry for response to your comment. I already committed the config files as the following:
 - https://github.com/hyperledger/cactus/tree/main/etc/cactus
I'd like to consider about how to enhance the config files on the other packages. I will make another issue again when my idea is put together.
