### ISSUE TITLE
Misspelling or does it contains some other meanings?

### ISSUE THREAD

**Issue by jscode017** [hyperledger/cactus#1053]
Currently reading codes trying to implement something for my hyperledger mentorship.
And find this:https://github.com/hyperledger/cactus/blob/6fbdca8625e1bb597a8b46186f4b3f2f919dab4c/packages/business-logic-plugin/BusinessLogicBase.ts#L34
Not sure if this(BisinessLogcPlugin) is just a misspelling or contains important meanings?

**Comment by petermetz** [comment]
@jscode017 Definitely looks like a typo to me. Should be Business Logic Plugin

**Comment by takeutak** [comment]
@jscode017 Thanks for your suggestion! This is only a misspelling. Would you mind if you post a pull-request about correcting it?

**Comment by petermetz** [comment]
https://github.com/hyperledger/cactus/pull/1101 is now merged, closing this one accordingly.

cc: @jscode017
