### ISSUE TITLE
feat(connector-besu): add getPastLogs web service

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1067]
### Description
As a ... I want to ... so that ....

(add more description and relevant links)

### Acceptance Criteria
1. First acceptance criteria
2. ...
3. ...

**Comment by awadhana** [comment]
Description:

The getsPastLogs method gets past logs that match the given options.


Please visit:
https://web3js.readthedocs.io/en/v1.3.4/web3-eth.html#getpastlogs

For more information regarding the method, it's parameters and returns.
