### ISSUE TITLE
feat(keychain-google-sm): complete request handler and endpoints

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cactus#1097]
### Description
As a developer, I want to complete the code to enable the endpoints
get-keychain-entry
set-keychain-entry
delete-keychain-entry (or maybe use set-keychain-entry with tags for deletion)
Also, write tests that use the API client instead of the plugin instance directly.

### Acceptance Criteria
1. Update openapi.json at packages/cactus-plugin-keychain-google-sm/src/main/json/openapi.json
2. Update the endpoints at packages/cactus-plugin-keychain-google-sm/src/main/typescript/webservices
3. UPDATE: We do not need the remote adapter unless the plugin is implemented in a non-NodeJS language
4. Update the test code at packages/cactus-plugin-keychain-google-sm/src/test/typescript/integration/plugin-keychain-google-sm.test.ts

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy @petermetz  @TonyRowntree @travis-payne

**Comment by petermetz** [comment]
cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by twiggins120** [comment]
I will work on this.
