### ISSUE TITLE
refactor(keychain): deprecate rotateEncryptionKeys method

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1108]
### Description

Introducing the `rotateEncryptionKeys()` method to the keychain API was a mistake (congrats Peter).
Let's purge it from the codebase entirely.

### Acceptance Criteria
1. Method is removed.
2. Test are still passing.
3. Container images are still building.

cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by sharath2106** [comment]
Hi @petermetz 

I'd like to take this up.

**Comment by ty-lazar** [comment]
> Hi @petermetz
> 
> I'd like to take this up.

I think @petermetz wants the interns to take this one

**Comment by petermetz** [comment]
@sharath2106 You got first dibs if you still want it. Assigning now.

**Comment by sharath2106** [comment]
@petermetz You should be getting a PR by tomorrow. Apologies for the delay!

**Comment by petermetz** [comment]
> @petermetz You should be getting a PR by tomorrow. Apologies for the delay!

@sharath2106 No worries, thank you again for the contribution!

**Comment by epartakki** [comment]
I can attempt this one!

**Comment by petermetz** [comment]
@epartakki It's been open for some time so I'd say it's okay for you to take it, thank you very much in advance! @sharath2106 I hope it's okay!
