### ISSUE TITLE
refactor: deprecate cactus-cockpit package

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1112]
### Description

Initially the cockpit package was great for testing, but it has outlived it's usefulness and now is just slowing down the build process for no good reason.

### Acceptance Criteria
1. The `@hyperledger/cactus-cockpit` is removed from the project

cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by Jeff-Ushry** [comment]
Working on it
