### ISSUE TITLE
refactor: eliminate endpoint constant classes

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1120]
### Description

We mostly migrated over to using the `openapi.json` files (by importing them) but there still remains a few endpoint constant files that are holding redundant information about operation IDs and HTTP paths/verbs.
We need to get rid of these and migrate the endpoint class implementations to importing the relevant openapi.json files instead.

`examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bamboo-harvest-endpoint-constants.ts`

### Acceptance Criteria
1. The entire project is covered, e.g. there are no more x-endpoint-constants.ts files anywhere in the code.
2. The openapi.json files are being imported instead so that there's a single source of truth for endpoint metadata (path, verb, operation ID)

cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by Leeyoungone** [comment]
I will do this! :)
