### ISSUE TITLE
style: fix OpenAPI spec linter warnings in endpoints 

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1126]
### Description

We have linter warnings about the endpoint classes having methods that do not declare their return types.
The workaround can be seen below that will declare explicitly the return type without having to construct any additional new types to map to the JSON files (open API specs)

```typescript
  public get oasPath(): typeof OAS.paths["/api/v1/plugins/@hyperledger/cactus-plugin-ledger-connector-fabric/run-transaction"] {
    return OAS.paths[
      "/api/v1/plugins/@hyperledger/cactus-plugin-ledger-connector-fabric/run-transaction"
    ];
  }

  public getPath(): string {
    return this.oasPath.post["x-hyperledger-cactus"].http.path;
  }

  public getVerbLowerCase(): string {
    return this.oasPath.post["x-hyperledger-cactus"].http.verbLowerCase;
  }

  public getOperationId(): string {
    return this.oasPath.post.operationId;
  }
```

### Acceptance Criteria
1. All linter warnings in the project that are about the OAS path objects in the endpoint classes' methods are fixed (no need to fix all linter warnings just the relevant ones)

cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by Leeyoungone** [comment]
May I take this one?

**Comment by petermetz** [comment]
> May I take this one?

@Leeyoungone Yup, all yours! :-)
