### ISSUE TITLE
refactor(connector-fabric): deprecate chain code compiler

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1131]
### Description

The chain code compiler has outlived it's usefulness. Remove it from the codebase.

`packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/chain-code-compiler.ts`

### Acceptance Criteria
1. References in documentation are searched for and cleaned up.
2. Test cases using it are deleted.
3. The class itself is deleted as well.

cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by Jeff-Ushry** [comment]
On it
