### ISSUE TITLE
test: ensure .test.ts ending for test code files

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1137]
### Description

We need a file naming scheme that makes it trivial to decide between which file is a test file and which isn't.
Most of the files already use the `.test.ts` suffix but not all.

### Acceptance Criteria
1. Find all test files that do not end with `.test.ts` and rename them accordingly
2. Read through BUILD.md looking for references to the test files and update the example commands according the rename you just did (if any references are found)
3. Read through CONTRIBUTING.md looking for references to the test files and update the example commands according the rename you just did (if any references are found)
4. Do a free text search (project wide) for references of `npx tap` to see if there's any other documentation files I've missed where example commands could be referencing the test cases that you just renamed.

cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by twiggins120** [comment]
I'll work on this.
