### ISSUE TITLE
docs: fix naming - use API Client instead of SDK

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1138]
### Description

We refactored the SDK packages to be called API client quite a while back and of course the documentation was only updated in certain places but not all.

For example the CONTRIBUTING.md file still refers to it as SDK which we should change.

```markdown
### Building the SDK

You do not need to do anything special to have the SDK sources generated and
compiled. It is all part of the `npm run build:dev:backend` task which you can run yourself
or as part of the CI script (`./tools/ci.sh`).

The SDK is itself just another package named `sdk` and can be dependend on by
other packages where applicable.

The SDK is designed to be a universal package meaning that it runs just fine in
browser and also NodeJS environments. This is very important as we do not wish
to maintain two (or more) separate SDK codebases and we also want as much of it
being generated automatically as possible (currently this is close to 100%).
```

(add more description and relevant links)

### Acceptance Criteria
1. CONTRIBUTING.md has been updated
2. Also check BUILD.md
3. Also check whitepaper.md (the English translation is enough)

cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by Leeyoungone** [comment]
May I take this one?

**Comment by petermetz** [comment]
@Leeyoungone All yours!
