### ISSUE TITLE
build(dev-container): add Rust toolchain (cargo, rustc, etc.)

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1143]
### Description

**Note: This is a good first issue, but on the estimated expertise level of `300`.**

As a contributor working on different programming languages I want to be able to get a cozy experience via the dev container the same way Typescript users have it so that I'm more productive and it's easier to get started with my contributions in general.

Example:
If someone wants to write a plugin in Rust, it's technically possible, but as it is today, they'd need to manually install and set up their Rust workflow within the container which gets especially annoying when you need to rebuild the container and your changes are lost.

### Acceptance Criteria
1. Dev container docker file is updated so that cargo, rustc are available
2. It is verified that rust code is possible to be built => the Vault keychain plugin's rust code.
3. Base image is not changed, we need Ubuntu 2004 and we need docker in docker.

cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by RafaelAPB** [comment]
@petermetz is anyone working on this?

**Comment by petermetz** [comment]
@RafaelAPB Not yet. My plan: if nobody does it 'til early next week then I'll take it upon myself, but it's up for grabs until then so if you'd like to go for it I'm happy to oblige. :-)

**Comment by RafaelAPB** [comment]
@petermetz this is probably very much needed for the Polkadot connector (more specifically for a Polkadot/Substrate test ledger). Either I or @CatarinaPedreira could take this (but later, as in mid-August/early September)

**Comment by petermetz** [comment]
> Either I or @CatarinaPedreira could take this (but later, as in mid-August/early September)

@RafaelAPB That timeline works for me as things stand right now. If it becomes more urgent in the meantime I may "steal" it back, but let's just see how it works out. :-)
In the meantime I can assign it to both you and @CatarinaPedreira if you like, just let me know.

**Comment by petermetz** [comment]
Expediting this one because we'll need Rust brought in as one of the default project dependencies on account of the Weaver+Cactus collaboration.
