### ISSUE TITLE
feat(examples): enhance the request feature on the examples/discounted-cartrade

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#1181]
**Is your feature request related to a problem? Please describe.**
To use examples/discounted-cartrade easily, the http-request feature on the examples/discouted-cartrade is needed.

**Describe the solution you'd like**
To add http-request feature on the examples/discounted-cartrade

**Comment by t-yasushi** [comment]
I'm working on this

**Comment by t-yasushi** [comment]
I issued a PR #1182 to solve part of this issue. 
In this PR, I update the cert and private key at default.json to activate trade process in discouted-cartrade.

**Comment by t-yasushi** [comment]
I issued a PR #1187 to solve the rest of the issue.
I create req_discounted_cartrade.py in example/discounted-cartrade.
This sends http request to discounted-cartrade after resistors indy data.
