### ISSUE TITLE
docs(connector-besu): document usage of besu private transactions

### ISSUE THREAD

**Issue by travis-payne** [hyperledger/cactus#1213]
### Description

Now private transactions have been implemented for Besu, the usage needs to be documented in the readme.md file.

**Comment by travis-payne** [comment]
I'm picking this one up

**Comment by petermetz** [comment]
@travis-payne Cool, thank you very much! FYI: I renamed the issue to be more specific (though I agree 100% that writing docs is a chore ;-) )
