### ISSUE TITLE
fix(keychain-aws-sm): ClassNotFoundException: org.openapitools.codegen.OpenAPIGenerator

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1301]
**Describe the bug**

The problem most likely is that some packages use a different version of the OpenAPI generator than others.
Most packages use 5.1.1 but some rolls with 5.2.0

**To Reproduce**

Build the project for the first time `yarn configure` and observe the crash during the build.
Once the crash has happened, run it a second time and observe that this time it succeeds (makes this a lower priority but it's still important due to this hitting people who are checking the code out for the first time).

**Expected behavior**

Build does not fail.

**Logs/Stack traces**

```sh
lerna ERR! yarn run codegen exited 1 in '@hyperledger/cactus-plugin-keychain-aws-sm'
lerna ERR! yarn run codegen stdout:
$ run-p 'codegen:*'
$ npm run generate-sdk

> @hyperledger/cactus-plugin-keychain-aws-sm@0.8.0 generate-sdk
> openapi-generator-cli generate -i ./src/main/json/openapi.json -g typescript-axios -o ./src/main/typescript/generated/openapi/typescript-axios/

Download 5.2.0 ...
Downloaded 5.2.0
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run codegen stderr:
/workspaces/cactus/node_modules/@openapitools/openapi-generator-cli/main.js:621
                error ? reject(new Error(stderr)) : resolve(stdout);
                               ^

Error: Error: Could not find or load main class org.openapitools.codegen.OpenAPIGenerator
Caused by: java.lang.ClassNotFoundException: org.openapitools.codegen.OpenAPIGenerator

    at /workspaces/cactus/node_modules/@openapitools/openapi-generator-cli/main.js:621:32
    at ChildProcess.exithandler (node:child_process:333:5)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
error Command failed with exit code 1.
ERROR: "codegen:openapi" exited with 1.
error Command failed with exit code 1.
lerna ERR! yarn run codegen exited 1 in '@hyperledger/cactus-plugin-keychain-aws-sm'
```

**Screenshots**

N/A

**Cloud provider or hardware configuration:**

Dev machine.

**Operating system name, version, build:**

The dev container.

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`main`

**Hyperledger Cactus Plugins/Connectors Used**

AWS SM keychain, but could be other packages as well.

**Additional context**

Since other packages could have the same issue, this needs to be fixed across the board as part of this task, meaning that a project wide free text search is recommended to discover inconsistencies of the OpenAPI generator version numbers.

**Comment by Leeyoungone** [comment]
hello! may I pick up this issue?

**Comment by Leeyoungone** [comment]
I think you were able to fix this issue through the new PR! 👍

**Comment by petermetz** [comment]
@Leeyoungone Thank you for double checking! Closing it then.
