### ISSUE TITLE
docs: create FEATURES.md

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cactus#1319]
**Is your feature request related to a problem? Please describe.**
Hopefully, this issue makes sense. Currently, there is no document on the project (please correct me if wrong) that allows a newcomer to quickly understand what Cactus can offer (possibly divided by categories).

**Describe the solution you'd like**
A document that lists each feature group (i.e., features from a package) with a general description. 
This list would contain only already implemented features

**Additional context**
Groups could be divided into technical, semantic, application, legal and governance ([source](https://arxiv.org/abs/2005.14282)) 
The Technical layer items would be all the connectors and packages that route information.
The Semantic layer would be packages (probably blps) that implement protocols, responsible for data semantics (what is an asset vs raw data), representation of state and identity, etc. The ODAP package is a good example.
The Application layer would realize applications built on top of the semantic and technical layers (e.g., carbon emission app uses connectors).
Legal and governance are higher-level layers that are mostly realized with specifications.
 

Example:

Cactus Feature List

Technical Layer:
-[Fabric Connector](https://github.com/hyperledger/cactus/tree/main/packages/cactus-plugin-ledger-connector-fabric) - allows connecting to a Hyperledger Fabric v1.x-2.x network.

[...]

Semantic Layer:
-ODAP - implements the Open Asset Digital Protocol draftv2. Does not include crash recovery.

etc...

**Comment by petermetz** [comment]
@RafaelAPB Could this be an addition to the ledger support matrix [1] instead of a standalone document? Or are they different enough to warrant a standalone one?

[1]: https://hyperledger-cactus.readthedocs.io/en/latest/support.html

**Comment by RafaelAPB** [comment]
@petermetz probably it's a good idea to add to that document. I think those matrixes are super important and thus should be on the README.md

**Comment by petermetz** [comment]
> @petermetz probably it's a good idea to add to that document. I think those matrixes are super important and thus should be on the README.md

@RafaelAPB Cool, then I recommend updating the matrix document instead of adding a new one. Also agreed that a link to the matrix document from the README.md is a no-brainer so would be happy to accept a change like that as well.

**Comment by RafaelAPB** [comment]
Seems good to me!
