### ISSUE TITLE
docs(API-table): enhance the API table document

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#1320]
**Is your feature request related to a problem? Please describe.**
The API functions on Cactus exist as follows:
  - deployContract
  - invokeContract
  - runTransaction
  - execSyncFunction
  - sendSignedTransaction
  - startMonitor / stopMonitor
  - ...
So it is needed to organize API table of Cactus function.

**Describe the solution you'd like**
@takeutak will organize the API table document.

**Comment by izuru0** [comment]
I will make the changes
