### ISSUE TITLE
ci: ensure sorted package.json files

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1341]
### Description

Consistency of the package.json files could be improved via enforcing in the CI that package.json files are always sorted.

https://www.npmjs.com/package/sort-package-json

### Acceptance Criteria
1. Not just the root package.json but also all child package json files are checked for being sorted.
2. CI fails if any of the package.json files are unsorted
3. There is a convenience npm (yarn) script that performs the sorting at development time so that people don't *ever* have to do it manually (which is a chore)

**Comment by Leeyoungone** [comment]
May I also take this one?

**Comment by petermetz** [comment]
```json
examples/cactus-example-carbon-accounting-backend/package.json
examples/cactus-example-carbon-accounting-business-logic-plugin/package.json
examples/cactus-example-carbon-accounting-frontend/package.json
examples/cactus-example-supply-chain-backend/package.json
examples/cactus-example-supply-chain-frontend/package.json
examples/cactus-example-supply-chain-business-logic-plugin/package.json
extensions/cactus-plugin-htlc-coordinator-besu/package.json
extensions/cactus-plugin-object-store-ipfs/package.json
packages/cactus-api-client/package.json
packages/cactus-cmd-api-server/package.json
packages/cactus-cmd-socketio-server/package.json
packages/cactus-common/package.json
packages/cactus-core/package.json
packages/cactus-core-api/package.json
packages/cactus-plugin-consortium-manual/package.json
packages/cactus-plugin-htlc-eth-besu/package.json
packages/cactus-plugin-htlc-eth-besu-erc20/package.json
packages/cactus-plugin-keychain-aws-sm/package.json
packages/cactus-plugin-keychain-azure-kv/package.json
packages/cactus-plugin-keychain-google-sm/package.json
packages/cactus-plugin-keychain-memory/package.json
packages/cactus-plugin-keychain-memory-wasm/package.json
packages/cactus-plugin-keychain-vault/package.json
packages/cactus-plugin-ledger-connector-besu/package.json
packages/cactus-plugin-ledger-connector-corda/package.json
packages/cactus-plugin-ledger-connector-fabric/package.json
packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
packages/cactus-plugin-ledger-connector-iroha/package.json
packages/cactus-plugin-ledger-connector-quorum/package.json
packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
packages/cactus-plugin-ledger-connector-xdai/package.json
packages/cactus-plugin-odap-hermes/package.json
packages/cactus-test-api-client/package.json
packages/cactus-test-cmd-api-server/package.json
packages/cactus-test-plugin-consortium-manual/package.json
packages/cactus-test-plugin-htlc-eth-besu/package.json
packages/cactus-test-plugin-htlc-eth-besu-erc20/package.json
packages/cactus-test-plugin-ledger-connector-besu/package.json
packages/cactus-test-plugin-ledger-connector-quorum/package.json
packages/cactus-test-tooling/package.json
```

**Comment by TonyRowntree** [comment]
packages/cactus-api-client/package.json
packages/cactus-cmd-api-server/package.json
packages/cactus-common/package.json
packages/cactus-core/package.json
packages/cactus-core-api/package.json
packages/cactus-plugin-consortium-manual/package.json
packages/cactus-plugin-htlc-eth-besu/package.json
packages/cactus-plugin-htlc-eth-besu-erc20/package.json
packages/cactus-plugin-keychain-aws-sm/package.json
packages/cactus-plugin-keychain-azure-kv/package.json
packages/cactus-plugin-keychain-google-sm/package.json
packages/cactus-plugin-keychain-memory/package.json
packages/cactus-plugin-keychain-memory-wasm/package.json
packages/cactus-plugin-keychain-vault/package.json
packages/cactus-plugin-ledger-connector-besu/package.json
packages/cactus-plugin-ledger-connector-corda/package.json
packages/cactus-plugin-ledger-connector-fabric/package.json
packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
packages/cactus-plugin-ledger-connector-iroha/package.json
packages/cactus-plugin-ledger-connector-quorum/package.json
packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
packages/cactus-plugin-ledger-connector-xdai/package.json
packages/cactus-plugin-odap-hermes/package.json
packages/cactus-test-api-client/package.json
packages/cactus-test-cmd-api-server/package.json
packages/cactus-test-plugin-consortium-manual/package.json
packages/cactus-test-plugin-htlc-eth-besu/package.json
packages/cactus-test-plugin-htlc-eth-besu-erc20/package.json
packages/cactus-test-plugin-ledger-connector-besu/package.json
packages/cactus-test-plugin-ledger-connector-quorum/package.json
packages/cactus-test-tooling/package.json
package.json
examples/cactus-example-carbon-accounting-backend/package.json
examples/cactus-example-carbon-accounting-business-logic-plugin/package.json
examples/cactus-example-carbon-accounting-frontend/package.json
examples/cactus-example-supply-chain-backend/package.json
examples/cactus-example-supply-chain-business-logic-plugin/package.json
examples/cactus-example-supply-chain-frontend/package.json
extensions/cactus-plugin-htlc-coordinator-besu/package.json
extensions/cactus-plugin-object-store-ipfs/package.json
