### ISSUE TITLE
feat(test-tooling): corda all-in-one docker image

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#143]
### Description
As a developer I want to have Cactus ship with an all in one Corda image so that I can write (relatively) lightweight and fully automated test cases where a ledger is brought up from scratch, used for testing and then stopped and cleaned up. Multiple containers of the same image must be able to co-exist on the same machine.

These files are examples of the same thing already done for Quorum and Besu in action (e.g. there are passing tests with contract deployment for them)

Ledger class:
`./packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts`

Test case using the Ledger class for test tooling:
`./packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.ts`

The same classes exist for Besu.

An example of the all in one image for Besu can be seen here:
https://github.com/petermetz/besu-docker-all-in-one
Notice how it uses docker build stages to combine together orion and besu's base images.

One thing that is not yet done in the besu all in one docker image (but sorely needed) is the possibility to inject a custom genesis JSON object through code directly from the tests, meaning that a test could generate it's own list of test account addresses with specific balances to create any kind of scenario.

### Acceptance Criteria
1. docker pull corda-all-in-one (or similar name) works out of the box
2. Avoid using docker volumes and host ports by default to make sure container instantiation is re-entrant e.g. I can blindly start multiple containers with the same image with default options and it doesn't start crashing because of volume/port conflicts.
3. Have a class CordaTestLedger in the `cactus-test-tooling` package that is responsible for managing the all in one docker image (can start, stop, destroy it and allows for customization) similarly as the class linked above (QuorumTestLedger)
4. Customizable initial state through parameters of the constructor/start method of the CordaTestLedger class.
5. A test case in the cactus-test-tooling package that verifies the image and the CordaTestLedger in action for deploying a hello world sort of contract. Very similar to this here: `packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.ts`
FYI: I'm working on REST API endpoints that expose contract compilation as a feature. Starting with solidity but would be nice to have kotlin/java as well for Corda contracts.

cc: @jonathan-m-hamilton @jweate

**Comment by jweate** [comment]
I am currently working on this!
