### ISSUE TITLE
fix(plugin-ledger-connector): Some of the plugin-ledger-connectors are using wrong Interface  Types in their class definitions

### ISSUE THREAD

**Issue by m-courtin** [hyperledger/cactus#1445]
**Describe the bug**

Some of the plugin-ledger-connectors are using wrong Interface  Types in their class definitions where the types for the deployContract() and the transact() functions are getting defined.

**To Reproduce**

In plugin-ledger-connector-quorum for example the class definition needs to implement "IPluginLedgerConnector<
      DeployContractSolidityBytecodeV1Request, DeployContractSolidityBytecodeV1Response,
      RunTransactionRequest, RunTransactionResponse >" but the deployContract() is using DeployContractSolidityBytecodeV1Request and RunTransactionResponse instead of the interface definition pair DeployContractSolidityBytecodeV1Request, DeployContractSolidityBytecodeV1Response.

Similar is the case for the besu connector.

**Expected behavior**

For all the connector class definitions the implementation needs to follow their interface definition and need to match in consistent way for all the connectors.

**Comment by petermetz** [comment]
@m-courtin Sounds good to me. My only nit: keep branches all lower-case if possible. (some git tooling/operating systems do not take kindly to certain edge cases that stem from mixed-case branch names)
