### ISSUE TITLE
feat(cmd-api-server): Refuse to run on NodeJS 10 by default

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#150]
### Description
As an ops/sec person I want to have safe defaults wherever possible so that (hopefully) my life doesn't get ruined by a data breach caused by unsecured software I deployed after failing to read the manual/fine print/etc.

NodeJS 10 sort of supports TLSv1.3 but not really. Meaning that there's a flag that can be set to accept TLSv1.3, but when it comes down to the implementation it's just not there and in fact throws exceptions if you try to use it:
https://github.com/nodejs/node/blob/v10.20.1/lib/_tls_common.js#L44

So my proposal here is to discontinue NodeJS v10 support and start having the minimum as NodeJS 12.
This also gives us some extra goodies like certain elliptic curve crypto features that came in with v12.

Another justification is that the current LTS Is already 12 and stable v14 is already out so we should keep up with the world.

### Acceptance Criteria
1. Cactus doesn't start on Node 10 by default, but possible to configure it so that it does work and uses TLS 1.2. This way people can opt in to less secure versions, but they won't get exposed unknowingly.
2. package.json file is updated to match these constraints

cc: @jonathan-m-hamilton  @sfuji822  @takeutak  @hartm

**Comment by jonathan-m-hamilton** [comment]
Discussed in maintainers call on moving to version 12
