### ISSUE TITLE
feat(core-api): add weaver protocol buffer definitions

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1523]
### Acceptance Criteria

1. Commit the protocol buffer definitions of Weaver to the Cactus Core API package
2. Set up automatic publishing of a Rust crate so that any time a commit is merged to main a new version of the crate is pushed with the protocol buffer definitions - this step is dependent on whether we want to also publish the generated Rust code for the protocol buffers or just the .proto files. If the latter then there's no need to set up the crate publishing *just yet*
3. Ensure Rama has signed off on adding the files (verbal sign-off has been acquired but also on the git commit log)
4. Ensure Typescript definitions are generated from the .proto files - figure out if this should be in it's own package or in one of the existing ones such as `core` or `cmd-api-server` etc.

**Comment by petermetz** [comment]
### Acceptance Criteria

1. Commit the protocol buffer definitions of Weaver to the Cactus Core API package
2. Set up automatic publishing of a Rust crate so that any time a commit is merged to main a new version of the crate is pushed with the protocol buffer definitions - this step is dependent on whether we want to also publish the generated Rust code for the protocol buffers or just the .proto files. If the latter then there's no need to set up the crate publishing *just yet*
3. Ensure Rama has signed off on adding the files (verbal sign-off has been acquired but also on the git commit log)
4. Ensure Typescript definitions are generated from the .proto files - figure out if this should be in it's own package or in one of the existing ones such as `core` or `cmd-api-server` etc.

**Comment by VRamakrishna** [comment]
@petermetz Submitted a PR to your branch: https://github.com/petermetz/cactus/pull/8.

**Comment by VRamakrishna** [comment]
@petermetz I think we should import the compiled versions (i.e., language-specific bindings) too. Presently, Weaver has these for JS, Go, and Java. Rust is being worked on.

**Comment by petermetz** [comment]
> @petermetz I think we should import the compiled versions (i.e., language-specific bindings) too. Presently, Weaver has these for JS, Go, and Java. Rust is being worked on.

@VRamakrishna Agreed, 100%, I added a new issue to the epic => https://github.com/hyperledger/cactus/issues/1556
