### ISSUE TITLE
refactor(ledger-connector-corda): add startMonitor features

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#1610]
**Is your feature request related to a problem? Please describe.**
On the current codes, some ledger-connectors (besu, quorum, corda, ...) does not have common API for monitoring block data on connected ledgers.
Corda has no block structure, but if some numbers of transactions are assumed as blocks, this feature can be developed.

This feature was already developed in cmd-socket-server and related ledger-connectors, but in case of merging those codes, we need to enhance the range.

**Describe the solution you'd like**
Add startMonitor feature to the above ledger-connector

**EPIC**
#1611

**Comment by petermetz** [comment]
Applies to Corda v4.8

**Comment by outSH** [comment]
@petermetz I have some questions regarding corda connector and possible monitoring implementation, could you answer them please?
- Does BLP (apiClient) ever need to call kotlin server directly? There're tests for that, but my assumption is that on production kotlin server could be strictly separated from the rest of the network.
- Why there's a single API for both kotlin and typescript services? They'll either diverge along the way, or one of the services will be obsolete, or am I missing something?
- Can we add `watchBlocks` endpoint to typescript component only, and different monitoring implementation endpoints on kotlin server (startMonitor, stopMonitor, getBlocks)?

**Comment by petermetz** [comment]
> Does BLP (apiClient) ever need to call kotlin server directly?

If the application is designed that way then yes. It is possible to design the application in such a way that the answer is no, but that limits certain options of course.

> There're tests for that, but my assumption is that on production kotlin server could be strictly separated from the rest of the network.

You could deploy it on a separate network if you wanted to, yes.

> Why there's a single API for both kotlin and typescript services? They'll either diverge along the way, or one of the services will be obsolete, or am I missing something?

The Typescript code is being redone to be the code for Corda v5. You just cannot see this on main yet but there's been a PR open for quite some time that we need to finalize and then merge (and then if you read the code on `main` it will make much more sense)

> Can we add watchBlocks endpoint to typescript component only, and different monitoring implementation endpoints on kotlin server (startMonitor, stopMonitor, getBlocks)?

If you'd like to, sure thing. Just keep in mind that Kotlin server is for Corda v4 and the Typescript code of the connector is for Corda v5 (in the near future as soon as we can finalize the PR for it)

**Comment by outSH** [comment]
@petermetz The PR you have in mind is https://github.com/hyperledger/cactus/pull/1860?
