### ISSUE TITLE
fix(api-server): shutdown hook configuration is using wrong config key

### ISSUE THREAD

**Issue by m-courtin** [hyperledger/cactus#1619]
**Describe the bug**

In the api-server constructor the evaluation for the activation / deactivation of the shutdown hook is based on the wrong configuration property so that it always is falling back to the default value and pre-configured value is not taken.

Depends on #1649

**Comment by m-courtin** [comment]
@petermetz: Can you please assign this issue onto my name as discussed yesterday

**Comment by petermetz** [comment]
@m-courtin You got it, thank you for reporting!
