### ISSUE TITLE
example supply-chain does not work running or debugging locally

### ISSUE THREAD

**Issue by elenaizaguirre** [hyperledger/cactus#1622]
**Describe the bug**

When you are running or debugging supply-chain-app locally, http://localhost:3200/bamboo-harvest-list cannot be accessed

**To Reproduce**

1. Run or debug supply-chain-app as described in readme file.
2. Try to access http://localhost:3200/bamboo-harvest-list from browser
3. Localhost rejects the connection

**Expected behavior**

supply-chain application should be displayed in the browser

**Comment by jagpreetsinghsasan** [comment]
Yes, I faced the same error.
