### ISSUE TITLE
test: stop binding to 0.0.0.0 where localhost is enough

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1624]
**Describe the bug**

Fix *all* the test cases where we are needlessly binding to all network interfaces instead of just the localhost. 

All tests should be able to pass by binding to either localhost or the specific private LAN IP of the primary network interface of the host machine. The latter is needed only for tests where multiple containers need to talk to each other, in all other cases localhost is enough.

Why though?
Because in certain environments (enterprise firewall+proxy hell) this can make or break the test execution at development time which is not good. It can be worked around by manually updating the tests to bind to localhost but that's an extra burden on the contributors which we do not want.

**To Reproduce**

It is unclear what kind/type of network configuration is needed, but we know almost for sure that it has to do with firewall/proxy/VPN software.

**Expected behavior**

**Logs/Stack traces**

```sh
************************************************
...
ok 25 should be truthy
ok 26 should be truthy
ok 27 should be strictly equal
not ok 28 Total Transaction Count of 1 recorded as expected. RESULT OK
---
operator: ok
expected: true
actual: false
at: <anonymous> (~/cactus/packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts:369:11)
stack: |-
Error: Total Transaction Count of 1 recorded as expected. RESULT OK
at Test.assert [as _assert] (~/cactus/node_modules/tape/lib/test.js:311:54)
at Test.bound [as _assert] (~/cactus/node_modules/tape/lib/test.js:96:32)
at Test.assert (~/cactus/node_modules/tape/lib/test.js:430:10)
at Test.bound [as true] (~/cactus/node_modules/tape/lib/test.js:96:32)
at ~/cactus/packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts:369:11
at processTicksAndRejections (node:internal/process/task_queues:96:5)
...
ok 29 should be truthy
ok 30 should be truthy
ok 31 should be strictly equal
not ok 32 Total Transaction Count of 2 recorded as expected. RESULT OK
---
operator: ok
expected: true
actual: false
at: <anonymous> (~/cactus/packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts:392:11)
stack: |-
Error: Total Transaction Count of 2 recorded as expected. RESULT OK
at Test.assert [as _assert] (~/cactus/node_modules/tape/lib/test.js:311:54)
at Test.bound [as _assert] (~/cactus/node_modules/tape/lib/test.js:96:32)
at Test.assert (~/cactus/node_modules/tape/lib/test.js:430:10)
at Test.bound [as true] (~/cactus/node_modules/tape/lib/test.js:96:32)
at ~/cactus/packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts:392:11
at processTicksAndRejections (node:internal/process/task_queues:96:5)
...
************************************************
```

**Screenshots**

N/A

**Cloud provider or hardware configuration:**

Dev machine.

**Operating system name, version, build:**

N/A

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`1.0.0-rc.2`

**Additional context**

https://chat.hyperledger.org/channel/cactus?msg=BvD5NC2RYEhn2LYSa

**Comment by charellesandig** [comment]
Hi @petermetz please add me to this one, thank you!

**Comment by petermetz** [comment]
> Hi @petermetz please add me to this one, thank you!

@charellesandig Done, sorry for the slow response and thank you!
