### ISSUE TITLE
refactor(sdk): improve (shorten) SDK method names

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#163]
### Description
As a developer I want to have an SDK that has method names that are sensible and not overly verbose so that my experience as a developer is much nicer when working with Cactus through the SDK.

Check out how the OpenAPI specs allow for `operationId` to override the method names that are otherwise inferred from the path (which can be pretty long for plugins because they include the fully qualified plugin ID)

https://swagger.io/docs/specification/paths-and-operations/#operations

### Acceptance Criteria
1. OpenAPI specs are refactored to have SDK method names that are no longer than 20 characters.

**Comment by petermetz** [comment]
FYI GFI: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by Leeyoungone** [comment]
I will take this!

**Comment by Leeyoungone** [comment]
I will take this!
