### ISSUE TITLE
fix(config-service): faulty shutdownHook definition in the Config-Schema definition

### ISSUE THREAD

**Issue by m-courtin** [hyperledger/cactus#1648]
**Describe the bug**

In the config-service of the api-server the configuration value for "shutdownHook" is not getting applied due to an issue in the reducer of the newExampleConfigEnv(). The reducer is not populating the shutdownHook configuration based on a faulty Config-Schema definition for the shutdownHook where "arg" and "env" are missing.

**Comment by m-courtin** [comment]
@petermetz: Can you please assign this issue onto my name

**Comment by petermetz** [comment]
@m-courtin You got it!
