### ISSUE TITLE
test(plugin-htlc-eth-besu): fix assert mixup in refund-endpoint-invalid

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1697]
In the bottom of the file:
packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint-invalid.test.ts
There is an assertion of a negative test case that verifies that incorrect
input correctly leads to a failure of the request.
It could be done by using a simple `rejects` assertion of Jest, but instead
a try catch block is used and there's some dead code in the form of some assertion
in there as well because the operation is never meant to succeed.

The problem is not just that it's dead code but also that it's making the test case
not work at all because if the operation ends up succeeding we are passing the test
anyway with the code as it is today.

```typescript
    try {
      const refundRequest: RefundReq = {
        id,
        web3SigningCredential,
        connectorId,
        keychainId,
      };
      const refundResponse = await api.refundV1(refundRequest);
      expect(refundResponse.status).toEqual(200);
    } catch (error: any) {
      expect(error.response.status).toEqual(500);
    }
```

**Comment by Leeyoungone** [comment]
May I pick up this issue?

**Comment by petermetz** [comment]
@Leeyoungone All yours, thank you in advance!
