### ISSUE TITLE
test(test-plugin-htlc-eth-besu): fix asserts new-contract-endpoint-invalid

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1698]
In the bottom of the file:
packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts
There is an assertion of a negative test case that verifies that incorrect
input correctly leads to a failure of the request.
It could be done by using a simple rejects assertion of Jest, but instead
a try catch block is used and there's some dead code in the form of some assertion
in there as well because the operation is never meant to succeed.

The problem is not just that it's dead code but also that it's making the test case
not work at all because if the operation ends up succeeding we are passing the test
anyway with the code as it is today.

```typescript
    try {
      const bodyObj: NewContractObj = {
        contractAddress: hashTimeLockAddress,
        inputAmount: 10,
        outputAmount: 0x04,
        expiration: DataTest.expiration,
        hashLock: DataTest.hashLock,
        receiver: DataTest.receiver,
        outputNetwork: "BTC",
        outputAddress: "1AcVYm7M3kkJQH28FXAvyBFQzFRL6xPKu8",
        connectorId: connectorId,
        web3SigningCredential,
        keychainId: "",
        gas: DataTest.estimated_gas,
      };
      const resp = await api.newContractV1(bodyObj);
      expect(resp).toBeTruthy();
      expect(resp.status).toEqual(200);
    } catch (error: any) {
      expect(error.response.status).toEqual(500);
    }
```

**Comment by Leeyoungone** [comment]
@petermetz May I pick up this issue?

**Comment by Leeyoungone** [comment]
Hey Peter, just wanted to say that the code you posted with the `try-catch` block (associated with this issue), isn't actually merged within the main branch. 

``` typeScript
    try {
      const bodyObj: NewContractObj = {
        contractAddress: hashTimeLockAddress,
        inputAmount: 10,
        outputAmount: 0x04,
        expiration: DataTest.expiration,
        hashLock: DataTest.hashLock,
        receiver: DataTest.receiver,
        outputNetwork: "BTC",
        outputAddress: "1AcVYm7M3kkJQH28FXAvyBFQzFRL6xPKu8",
        connectorId: connectorId,
        web3SigningCredential,
        keychainId: "",
        gas: DataTest.estimated_gas,
      };
      const resp = await api.newContractV1(bodyObj);
      expect(resp).toBeTruthy();
      expect(resp.status).toEqual(200);
    } catch (error: any) {
      expect(error.response.status).toEqual(500);
    }
```
I know this is an easier fix if we Jestify the test file (and @awadhana might be in the process of working on that file, I'm not sure). But if you'd like I could try to Jestify this file and solve this issue! If I do Jestify this issue, it'll be good practice, and if not I can definitely wait till this file gets merged within the main branch. What are your thoughts?

**Comment by petermetz** [comment]
> @petermetz May I pick up this issue?

Yup, assigning now.

@Leeyoungone Yeah I probably saw the code on one of Hana's branches and not on the main branch. Which makes me think that Hana has already Jestified it. What you can do in the scope of this issue is to base your PR on Hana's PR that is jestify-ing this one and then apply the specific fix on top of that and mark the PR as dependent on Hana's PR. Then eventually both will end up on main and in the right order.

**Comment by Leeyoungone** [comment]
@petermetz Sounds good!! I'll do that :)
