### ISSUE TITLE
API for Ledger Plugin

### ISSUE THREAD

**Issue by sfuji822** [hyperledger/cactus#178]
**Is your feature request related to a problem? Please describe.**
**Ledger Plugin** is introduced in Cactus architecture to enable communicating various Ledger to be integrated. We need a NodeJS friendly API, which absorbs difference between Blockchain platforms. 

**Describe the solution you'd like**
Define **_Ledger Plugin API_** which mandates to be implemented on every implementation of Ledger Plugins for specific blockchain platform.

**Describe alternatives you've considered**
We may start with delivering actual codes to figure out common interface, or we can define API specification on whitepaper.

**Additional context**
Takuma and I is planning to post PR regarding this issue.

**Comment by sfuji822** [comment]
solved by PR#217.

**Comment by petermetz** [comment]
> solved by PR#217.

Closing based on the above.
