### ISSUE TITLE
docs: changes to BUILD.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by ruzell22** [hyperledger/cactus#1792]
**Is your feature request related to a problem? Please describe.**
Based on experience, recommended NodeJS to be used should be v16.13.1 and npm to v8.1.2 to progress smoothly in BUILD.md and CONTRIBUTING.md. Also, we've encountered problems with some codes in BUILD.md and CONTRIBUTING.md and found an alternative that will give an output of 'passed'.

**Describe alternatives you've considered**
**for BUILD.md**

NodeJS v16.13.1, npm v8.1.2 (we recommend using the Node Version Manager (nvm) if available for your OS)
•	nvm use 16.13.1
For example, you can _run a ledger single status endpoint test_ via the REST API with this command:
•	npx tap --ts --timeout=600 packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint.test.ts

**for CONTRIBUTING.md**

Integration test
•	npx tap --ts --timeout=600 packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
Unit test
•	npx jest packages/cactus-common/src/test/typescript/unit/objects/get-all-method-names.test.ts

**Comment by ruzell22** [comment]
Hello @petermetz . I created a new ticket for the suggestions of changes in documentation, can you assign me on this ticket? Thank you.

**Comment by petermetz** [comment]
@ruzell22 Yup, assigning now. Thank you very much!
