### ISSUE TITLE
test(api-client): fix flaky socketio-api-client.test

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1804]
**Describe the bug**

The `packages/cactus-api-client/src/test/typescript/unit/socketio-api-client.test.ts` appears to be failing intermittently.

**To Reproduce**

Run it through the CI enough times to make it fail. Observe that it works sometimes and not other times.

**Expected behavior**

Tests should be stable, e.g. always failing or always succeeding with a given revision of the code.

**Logs/Stack traces**

```sh
Summary of all failing tests
FAIL packages/cactus-api-client/src/test/typescript/unit/socketio-api-client.test.ts (15.777 s)
SocketIOApiClient Tests › Sync Request Tests › Returns decoded response from the validator

thrown: "Exceeded timeout of 3000 ms for a hook.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

    276 |
    277 |   describe("Sync Request Tests", function () {
> 278 |     beforeEach(async () => {
        |     ^
    279 |       // Connect client and server sockets
    280 |       testServer.on("connection", (socket) => {
    281 |         log.debug("Server socket connected", socket.id);

    at packages/cactus-api-client/src/test/typescript/unit/socketio-api-client.test.ts:278:5
    at packages/cactus-api-client/src/test/typescript/unit/socketio-api-client.test.ts:277:3
    at Object.<anonymous> (packages/cactus-api-client/src/test/typescript/unit/socketio-api-client.test.ts:196:1)
```

**Cloud provider or hardware configuration:**

GitHub Action Runner for the Cactus CI

**Operating system name, version, build:**

Ubuntu-20.04

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`1.0.0-rc.3`

@outSH

**Comment by outSH** [comment]
@petermetz 
I've just executed this test over 800 times on local VM and didn't find any errors, I assume this is probably due to periodic low performance of CI environment. I've increased the timeouts for all tests (3s -> 5s), and separate setup timeout (3s -> 1 minute). Let's see if this solves the issue :)

**Comment by petermetz** [comment]
@outSH Great! Thank you very much! I agree, I'm pretty sure that the free VMs we get allocated for the GitHub CI jobs are heavily throttled in the hypervisor level somehow so they are probably pretty "weak" even compared to a regular laptop.
