### ISSUE TITLE
docs(contributing-md): dedicated section for test automation

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#187]
### Description
As a developer/contributor I want to have documentation on the testing protocol/framework/library/patterns used by Cactus so that I can get onboard quickly and write tests for my contributed code changes without having to research everything piece by piece and reverse engineer existing tests at the same time.

Added this based on a request during our weekly call yesterday.

### Acceptance Criteria
1. CONTRIBUTING.md is updated with a dedicated section
2. TAP is explained
3. Code example are included
4. Run single test example included
5. Run all tests example is included
6. Debugging a test case with Visual Studio Code with source map support is included
7. Keep separate unit-test as module (e.g. xx plugin) and integration-test as SDK
8. Make sure SDK build is successfully done
9. Exclude test on running exampled apps (since those apps are not in scope of Cactus and integration-test should not be depended on them)

cc: @jonathan-m-hamilton @takeutak @sfuji822

**Comment by sfuji822** [comment]
I would like to see your guidance to cover further criteria:
- Keep separate unit-test as module (e.g. xx plugin) and integration-test as SDK
- Make sure SDK build is successfully done
- Exclude test on running exampled apps (since those apps are not in scope of Cactus and integration-test should not be depended on them)

**Comment by petermetz** [comment]
> I would like to see your guidance to cover further criteria:
> 
> * Keep separate unit-test as module (e.g. xx plugin) and integration-test as SDK
> * Make sure SDK build is successfully done
> * Exclude test on running exampled apps (since those apps are not in scope of Cactus and integration-test should not be depended on them)

@sfuji822 Thank you, added these to the acceptance criteria in the description!
