### ISSUE TITLE
docs(contributing-md): github Desktop on Windows know about the file path length solution

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#188]
**Describe the bug**

When checking out the project via Github Desktop, it crashes because of too long paths.

**To Reproduce**

Attempt to check out the project on Github Desktop

**Expected behavior**

Github Desktop does not crash.

**Screenshots**

![image](https://user-images.githubusercontent.com/1583231/84812865-ef825100-afc3-11ea-819f-3b75a8380316.png)

**Operating system name, version, build:**

![image](https://user-images.githubusercontent.com/1583231/84812954-0d4fb600-afc4-11ea-9bc3-31dfdf56b122.png)

**Additional context**

The CONTRIBUTING.md guide specifically says that one should check out the code via Github Desktop so this is an issue of high importance due to how newcomers to the project might get turned off if the project can't even be cloned properly...

cc: @hartm @jonathan-m-hamilton @sfuji822 @takeutak

**Comment by petermetz** [comment]
Suggested resolution: compress the directory structure where necessary to avoid the file paths going over the length limit.
As an alternative we could add something to the documentation about how to fix the issue within the configuration of Github Desktop. This option may not even be viable if it turns out that there is no configuration exposed for the path lengths in Github Desktop (I took a quick look just now and couldn't find anything related to advanced git configuration options)

**Comment by hartm** [comment]
I didn't spent much time on this, but when I ran into this issue on Monday, I couldn't figure out how to get it working with Github desktop either.  Fixing the command line interface didn't seem to propagate into the desktop client.

We should probably also modify the documentation to recommend avoiding using Github desktop.  It's also complicated to do commits properly in desktop.

**Comment by petermetz** [comment]
> I didn't spent much time on this, but when I ran into this issue on Monday, I couldn't figure out how to get it working with Github desktop either. Fixing the command line interface didn't seem to propagate into the desktop client.
> 
> We should probably also modify the documentation to recommend avoiding using Github desktop. It's also complicated to do commits properly in desktop.

+1 for updating the documentation to explicitly suggest avoiding Github Desktop vs. the current state which is to recommend it.

**Comment by sfuji822** [comment]
I personally encountered this error in long time ago, and you can resolved this with configuring your git client 'core.longpaths' option enabled.

> git config --global core.longpaths true

Please see https://github.com/desktop/desktop/issues/8023 for your information.

I hope this helps you to solve the issue.
