### ISSUE TITLE
docs(examples): cross-ledger CRUD in the new architecture

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#189]
### Description

As a developer/contributor I want to have updated documentation with a proper, end to end example demonstrating how to develop applications with Cactus, so that I am not confused about the fact that (currently) there is no such documentation since we've moved over to the new architecture.

### Acceptance criteria

1. Demonstrates consortium with multiple members and their nodes
2. Demonstrates intra-node routing in action
3. Demonstrates cross ledger CRUD capabilities for a business logic plugin
4. SOLID principles are kept for the example app as well not just the core cactus code: https://en.wikipedia.org/wiki/SOLID
5. Short, deterministic script in the mean README.md file that can be executed by anyone to verify if the example is working.
6. Implement and leverage the keychain in-memory implementation (for demonstration purposes only)

### The original description of this issue before being refactored:

> ### Description
> As a developer/contributor I want to have updated documentation about the simple asset transfer demo that I saw during the Hyperledger Global Forum 2020 talk so that I am not confused about the fact that (currently) there is no such documentation since we've moved over to the new architecture.
> 
> Of course this depends on the new architecture reaching a level of maturity where the simple asset transfer case can actually be implemented.
> 
> ### Acceptance Criteria
> 1. The simple asset transfer use-case is re-written from scratch to match the new arch
> 2. The new documentation closes the loop regarding asset export verification and error handling as well (thanks to Arnaud for pointing out the lack of these)
> 
> cc: @hartm @sfuji822  @takeutak  @jonathan-m-hamilton
>

**Comment by sfuji822** [comment]
Agree. We should have documentation about the simplest use case which execute transfer a asset on one ledger to another.
FUJITSU is planning to provide a demo application which execute to transfer ownership of Car asset when the some tokens are transferred from buyer to seller with combination of Fabcar app on HLF and plain api on geth.
Where the documentation should be placed in whitepaper ?

**Comment by petermetz** [comment]
> Agree. We should have documentation about the simplest use case which execute transfer a asset on one ledger to another.
> FUJITSU is planning to provide a demo application which execute to transfer ownership of Car asset when the some tokens are transferred from buyer to seller with combination of Fabcar app on HLF and plain api on geth.
> Where the documentation should be placed in whitepaper ?

Thank you @sfuji822 Best place would be in my opinion is to have a mention of it in the second section where the use-cases are located: https://github.com/hyperledger/cactus/blob/master/whitepaper/whitepaper.md#21-ethereum-to-quorum-asset-transfer

One ask I have: Since this issue is for the asset transfer example using **the new architecture** that we introduced in March, please make sure to update the example of yours to that if you want to close this issue based on that PR. This is the same comment I raised here about using the existing packages as dependencies and the build format in general: https://github.com/hyperledger/cactus/pull/227/files#r457685996

**Comment by petermetz** [comment]
Update: Will break this into two different issues where one is about data query/joining across ledgers and the second issue is specifically about asset transfer (exports).
Second one will be moved to a later milestone so we can close out the 0.2.0 milestone as soon as #308 is merged.
