### ISSUE TITLE
build(lerna): evaluate lerna-lite migration

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1890]
Determine if we could migrate from upstream lerna to this fork given that
the upstream repo has not been receiving too much maintenance lately.

https://github.com/ghiscoding/lerna-lite

One upside for sure is that it would have the `--signoff` flag supported: https://github.com/lerna/lerna/pull/2897#issuecomment-1036641101

**Comment by johnhomantaring** [comment]
@petermetz please assign this to me

**Comment by petermetz** [comment]
> @petermetz please assign this to me

@johnhomantaring Done, thank you!
