### ISSUE TITLE
docs: Pull request template

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cactus#1894]
**Is your feature request related to a problem? Please describe.**
Pull requests are not standardized by a template

**Describe the solution you'd like**
Create a pull request template (possibly compatible with what other Hyperledger projects are doing) 

**Describe alternatives you've considered**
Ad-hoc structures for PRs (also fine)

**Additional context**
It is very useful to have some patterns when analysing/approving PRs in batches, namely high-level description, names of packages tackled, related issues, etc.

**Comment by petermetz** [comment]
@RafaelAPB Closing as duplicate.
