### ISSUE TITLE
test: fix yarn test:all on GCP instances

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cactus#1904]
**Describe the bug**

I spawn an Ubuntu 20 VM, installed java 8, latest docker and node 16.13, run configure (sucess) and then npm run test:all. There are tests that fail

**To Reproduce**
Spawn a VM on Google Cloud ( c2-standard-8, 70gb SSD 8 cores, 32gb ram), run npm configure. After that run npm run ™test:all

**Expected behavior**

The OpenAPI tests fail, always. Part of them:
FAIL  packages/cactus-plugin-keychain-vault/src/test/typescript/integration/openapi/openapi-validation.test.ts 8 failed of 22 14s
 ✖ Error: Request failed with status code 500
 ✖ Error: Request failed with status code 500
 ✖ Error: Request failed with status code 500
 ✖ Error: Request failed with status code 500
 ✖ Endpoint setKeychainEntryV1 with fake=4: response.status === 400 OK
 ✖ TypeError: _b.data.map is not a function
 ✖ Endpoint getKeychainEntryV1 with fake=4: response.status === 400 OK
 ✖ TypeError: _b.data.map is not a function

[**Logs/Stack traces**
](https://gist.github.com/RafaelAPB/df52004cf5bda1b7538a6ebacc16b15f)

**Operating system name, version, build:**

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**
 
commit ed6e16413f00031392451c4d4896903fece3a7c6

**Comment by petermetz** [comment]
@RafaelAPB Please re-run with the latest main now that this one has been merged:
https://github.com/hyperledger/cactus/pull/1861

**Comment by RafaelAPB** [comment]
@petermetz the majority of the tests are passing, except for 
FAIL examples/cactus-example-supply-chain-backend/src/test/typescript/unit/api-surface.test.ts
FAIL examples/cactus-example-supply-chain-backend/src/test/typescript/integration/api-surface.test.ts
  FAIL examples/cactus-example-carbon-accounting-backend/src/test/typescript/unit/api-surface.test.ts
FAIL examples/cactus-example-carbon-accounting-backend/src/test/typescript/integration/api-surface.test.ts

(I've sent logs via Discord, let's discuss and then post an answer here).

**Comment by RafaelAPB** [comment]
Update, looks like all tests pass. 
Test Suites: 118 passed, 118 total
Tests:       233 passed, 233 total
Snapshots:   0 total
Time:        916.707 s

Thanks, @petermetz

**Comment by petermetz** [comment]
> Update, looks like all tests pass. Test Suites: 118 passed, 118 total Tests: 233 passed, 233 total Snapshots: 0 total Time: 916.707 s
> 
> Thanks, @petermetz

@RafaelAPB Hell yeah! Thank you very much for the testing, re-testing and raising the issue in general!
