### ISSUE TITLE
Besu's all in one container - choosing network

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cactus#191]
**Is your feature request related to a problem? Please describe.**
Hyperledger Besu allows users to create nodes that can interact with different networks (private network by default, Ethereum mainnet, Ropsten testnet, etc).
The network can be chosen by feeding a parameter when the node is started: ``besu --network=dev``. At this moment, the besu all in one container, initiates a Besu node on the default network. It would be desirable for users to choose with which networks the node can interact with.

**Describe the solution you'd like**
The possibility to pass a parameter "network" to Besu's constructor, that indicates in which network it will be deployed.

**Additional context**
More at: https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Starting-node/

**Comment by petermetz** [comment]
@RafaelAPB Do I remember correctly that you already fixed this one with a PR of yours? Or was there something else why we should keep this open still?

**Comment by RafaelAPB** [comment]
@petermetz Yes, PR #196.
