### ISSUE TITLE
docs(readme): update chat from rocketchat to discord

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1937]
Right now the readme talks about the old (and now obsolete) RocketChat channel that we used to have.
We need to replace that with discord.

**Comment by Ejashba** [comment]
I'll PR this shortly

**Comment by petermetz** [comment]
> I'll PR this shortly

@Ejashba Great, thank you so much!

**Comment by petermetz** [comment]
@Ejashba FYI: You can also put this in your commit message of the PR (in the body of the message, on a new line) `Fixes #1937` which will trigger the bots to auto-close this issue when your PR gets merged.

**Comment by AbhinavMir** [comment]
https://github.com/hyperledger/cactus/pull/1964

Have opened a PR since this issue seems to be 10+ day old. Pending review @petermetz .
