### ISSUE TITLE
test(connector-iroha): fix and unskip run-transaction-endpoint-v1.test

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1957]
## Description

Currently this  test case is being skipped due to issues with the Iroha AIO
image:
`packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts`

## Acceptance criteria

1. The mentioned test is once again part of the CI and it passes consistently.

**Comment by Leeyoungone** [comment]
Hey @petermetz, just wanted to let you know that I've ran the test case at least 20 times (without any changes except not skipping the test cases anymore) and it has passed every single one of them. I've put up an issue mentioning this "fix" where I got rid of the `.skip`, let me know your thoughts

**Comment by petermetz** [comment]
> Hey @petermetz, just wanted to let you know that I've ran the test case at least 20 times (without any changes except not skipping the test cases anymore) and it has passed every single one of them. I've put up an issue mentioning this "fix" where I got rid of the `.skip`, let me know your thoughts

@Leeyoungone Nice, let's see how it goes. I don't remember for sure if we skipped it because it wasn't working at all or if it was flaky. We can start not skipping it and monitor the CI runs on unrelated PRs for failures due to this test case (if it starts being flaky we'll have to reverse your change and reopen this issue until we figure out the reason for the flaky execution of the test case)

**Comment by Leeyoungone** [comment]
@petermetz sounds good! thanks for your thoughts :))
