### ISSUE TITLE
ci: bump NodeJS v14 and v16 minor versions to latest

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1980]
Ensure that all the NodeJS versions that we 
1. Use for the CI 
2. Mention in the docs
3. Use for the VSCode dev container

are all upgraded to the latest minor versions (so don't upgrade out of the LTS major versions)

Why? Because the Angular CLI started requiring v16.10.x or later and right now
we are running the CI with something below that which makes this PR fail the CI
https://github.com/hyperledger/cactus/pull/1971

Logs: [upgrade_angular_node_16_10_minimum_version_build-containers.log](https://github.com/hyperledger/cactus/files/8516344/upgrade_angular_node_16_10_minimum_version_build-containers.log)

**Comment by aldousalvarez** [comment]
Hi @petermetz  Can you assign me on this one. Thank you

**Comment by petermetz** [comment]
> Hi @petermetz Can you assign me on this one. Thank you

@aldousalvarez Yup, done. Thank you!
