### ISSUE TITLE
ci: add yaml workflow file for semantic-pull-request action

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1987]
**Describe the bug**

Right now we have the out of the box version of the action coming straight from the marketplace with whatever default configuration that uses.
The issue with this is that it is flaky: it randomly gets stuck in a way that a perfectly good PR is blocked from being merged just because the semantic PR check is not executing for whatever reason. This is annoying as a maintainer because it reduces our velocity & PR throughput (which is already something we need to improve upon)

**To Reproduce**

Unclear. It comes and goes.

**Expected behavior**

The check is stable, executes every time reliably without issues.

We should use an explicit yaml workflow file for configuration and the latest version of the action from here:
https://github.com/marketplace/actions/semantic-pull-request

**Logs/Stack traces**

N/A

**Screenshots**

![Screenshot from 2022-04-22 10-52-49](https://user-images.githubusercontent.com/1583231/164768851-e49c27f1-50de-476a-a7c4-e7cbbb7c0d05.png)

**Cloud provider or hardware configuration:**

GitHub Hosted Action Runners / Marketplace

**Operating system name, version, build:**

N/A

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

N/A

**Hyperledger Cactus Plugins/Connectors Used**

N/A

**Additional context**

This is a problem that is affecting multiple pull requests at the moment and it's not the first time that the issue randomly popped up. It probably would disappear again in a few days but I'd rather us try to go for a stable fix so that it's never coming back.

**Comment by AbhinavMir** [comment]
Hi Peter, which file in `./github` is this described in?
