### ISSUE TITLE
fix(security): close DDoS vulnerability in eth tx consistenty strategy

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#2001]
## Description

The application performs some repetitive tasks in a loop and defines the number of times to perform the loop according to user input. A very high value could cause the application to get stuck in the loop and to be unable to continue to other operations.

Affected files are all the eth flavored connector plugins that have the `consistencyStrategy` request parameter when executing transactions.

- `packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts`
- `packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts`
- `packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts`

```typescript
    do {
      tries++;
      timedOut = Date.now() >= startedAt.getTime() + timeoutMs;
      if (timedOut) {
        break;
      }

      txReceipt = await this.web3.eth.getTransactionReceipt(txHash);
      if (!txReceipt) {
        continue;
      }

      const latestBlockNo = await this.web3.eth.getBlockNumber();
      confirmationCount = latestBlockNo - txReceipt.blockNumber;
    } while (confirmationCount >= consistencyStrategy.blockConfirmations);
```

## Impact

An attacker could input a very high value, potentially causing a denial of service (DoS).

## Remediation Recommendation

Don't base a loop on loosely validated user-provided data. The range should be limited. Always include a maximum value for each user input in the openapi.json specs.

Change the maximum for allowed block count to 20 thousand (a little over what the ethereum main net confirms in a 72 hour period according to the latest statistics at time of this writing: https://ycharts.com/indicators/ethereum_blocks_per_day

## Breaking Change Discussion

Fixing this will be a breaking change, because previously valid requests will now get rejected by the API server.
An argument could be made that it's only a breaking change for those who were previously sending malicious requests and for no one else and therefore it is not really a breaking change even though it technically is.

@izuru0 @takeutak @jagpreetsinghsasan Please weigh in on the question presented in `Breaking Change Discussion`

**Comment by jagpreetsinghsasan** [comment]
Can we fix it by having a specified time delay in-between requests instead of limiting the range?

**Comment by jagpreetsinghsasan** [comment]
Thanks @petermetz for descriptive reasoning. And I agree 100% with the fact that, layering the security measures is the best way out.

**Comment by aldousalvarez** [comment]
Hello @petermetz Can you assign me on this one? Thanks

**Comment by petermetz** [comment]
> Hello @petermetz Can you assign me on this one? Thanks

@aldousalvarez Done, than kyou!

**Comment by petermetz** [comment]
> BLOCKER/ISSUE: packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts - this file doesnt have any consistencyStrategy imports or usage.

@aldousalvarez My bad, `packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts` can be skipped.
