### ISSUE TITLE
Cannot find simple_asset_transfer folder inside examples folder

### ISSUE THREAD

**Issue by lucianoacsilva** [hyperledger/cactus#201]
Hello,

When following the tutorial of **simple_asset_transfer** in the docs, I could not find the **simple_asset_transfer** folder in the repo, and the **Fabric** and **Quorum** ones either. Is the tutorial not updated?

**Comment by petermetz** [comment]
@lucianoacsilva Thanks for checking it out!

Do you mean this folder? 
https://github.com/hyperledger/cactus/tree/master/contribs/Accenture-BIF/core/examples/simple-asset-transfer

**Comment by petermetz** [comment]
> Is the tutorial not updated?

That particular folder will not be updated going forward but we are working on the fresh version that works with the latest code.
Basically what's in the `./contribs` folder is the original code from both Accenture and Fujitsu that we just kept there for reference.

**Comment by lucianoacsilva** [comment]
Thanks, @petermetz !!

**Comment by petermetz** [comment]
> Thanks, @petermetz !!

No worries @lucianoacsilva 
Would you mind letting me know how you became aware of the simple asset transfer example? I want to make sure whereever that was, we update it so that the information I just gave you is readily available instead of people having to search like you did (sorry about that).

**Comment by petermetz** [comment]
@lucianoacsilva 
Also note: you can follow this issue for the updated simple asset transfer example so that whenever it does become available (hopefully soon) you get notified:
https://github.com/hyperledger/cactus/issues/189
