### ISSUE TITLE
chore(release): missing @hyperledger/cactus-cmd-socket-server npm package

### ISSUE THREAD

**Issue by outSH** [hyperledger/cactus#2069]
There's no `@hyperledger/cactus-cmd-socket-server:1.0.0` package in official NPM repository. It's required by socketio-based connector plugins (validators). Without this dependency, building of validator docker images fail. These images are required by electricty-trade and asset-trade sample apps, so without them, it's impossible to run them through the docker environment.

I'm pretty sure this package was available in NPM earlier on, please restore it if possible.

@izuru0 @jagpreetsinghsasan @petermetz

**Comment by AbhinavMir** [comment]
Is it possible that cactus-cmd-socket-server has shifted to [cactus-cmd-api-server](https://www.npmjs.com/package/@hyperledger/cactus-cmd-api-server)?

**Comment by petermetz** [comment]
@outSH Do you know for a fact that it used to be there?

**Comment by outSH** [comment]
@petermetz No, I'm not 100% sure. Nevertheless, it would be nice to have it on npm like the other packages, so please upload it if possible.

**Comment by outSH** [comment]
@petermetz Now that https://github.com/hyperledger/cactus/issues/2105 is merge and the name of package is consistent, can you publish this package to npm? I need to use it in some other Dockerfiles

**Comment by petermetz** [comment]
@outSH Apologies for the delay! Yes, I'll publish a new release with this package included ASAP!

**Comment by petermetz** [comment]
Re-opening until we can fix the release automation problems.

**Comment by petermetz** [comment]
@outSH I think I already said it but just to be sure pinging here as well: v1.1.2 artifacts are up on npmjs.com now.
