### ISSUE TITLE
chore(tools): Consolidate Docker All In One Images, Publishing

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#207]
### Description
As a developer I want to have a consistent view of the images maintained by Cactus for testing so that it's not confusing to locate the besu or the quorum all in one images for example (both of which at the moment are just dumped under Peter's personal handle because it was the path of least resistance at the time).

Context: We have 2 all-in-one images that are designed for testing already (besu, quorum) and two more are in the works: Jacob is working on Corda and Sownak is doing Fabric 1.4.x

Links to existing images that need to be moved into Cactus (because our code references the images via DockerHub as it is right now):
- https://github.com/petermetz/besu-docker-all-in-one
- https://github.com/petermetz/quorum-docker-all-in-one

The tasks/issues for Corda and Fabric:
#132 
#143 

### Acceptance Criteria
1. Images are all located under `./tools/docker/$LEDGER_NAME-all-in-one/` directory trees
2. Publishing of said images is set up as part of the CI, images go to the Github image registry or whatever else is preferred by HL

cc: @ryjones @takeutak  @sfuji822 @jonathan-m-hamilton @jweate @sownak

**Comment by ryjones** [comment]
https://hub.docker.com/repository/docker/hyperledger/cactus/

**Comment by petermetz** [comment]
> https://hub.docker.com/repository/docker/hyperledger/cactus/

Thank you Ry! I'll get going with the rest of it

**Comment by ryjones** [comment]
If you need more repos, let me know.

**Comment by sfuji822** [comment]
Thanks for templating the way to provide a testing environment. FUJITSU is preparing another docker images to add for ethereum/go-client and hyperledger fabric following these new criteria.
