### ISSUE TITLE
chore(cmd-socketio-server): rename package to match directory name

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#2105]
**Describe the bug**

The package is called `cactus-cmd-socket-server` while the directory is called `cactus-cmd-socketio-server`

**To Reproduce**

Look at the package and the directory names.

**Expected behavior**

Package and directory names match exactly. Package should be renamed to match the directory name.

cc: @outSH @izuru0 @takeutak

**Comment by outSH** [comment]
> **To Reproduce**
> 
> Look at the package and the directory names.

:heart:
