### ISSUE TITLE
Documentation update required.

### ISSUE THREAD

**Issue by aviral727** [hyperledger/cactus#2139]
As suggested by @petermetz a small shell command fix while manually building the package is to be added in the documentation. @outSH

**Comment by RafaelAPB** [comment]
For macOS:

error /Users/rafaelapb/Projects/cactus-with-branches/node_modules/indy-sdk: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/rafaelapb/Projects/cactus-with-branches/node_modules/indy-sdk
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@14.19.1 | darwin | x64
gyp info find Python using Python version 3.8.8 found at "/Users/rafaelapb/opt/anaconda3/bin/python3"
gyp info spawn /Users/rafaelapb/opt/anaconda3/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/rafaelapb/Projects/cactus-with-branches/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rafaelapb/Projects/cactus-with-branches/node_modules/indy-sdk/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rafaelapb/Projects/cactus-with-branches/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rafaelapb/Library/Caches/node-gyp/14.19.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/rafaelapb/Library/Caches/node-gyp/14.19.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/rafaelapb/Projects/cactus-with-branches/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/rafaelapb/Library/Caches/node-gyp/14.19.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/rafaelapb/Projects/cactus-with-branches/node_modules/indy-sdk',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/indynodejs/src/indy.o
  SOLINK_MODULE(target) Release/indynodejs.node
ld: library not found for -lindy
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/indynodejs.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rafaelapb/Projects/cactus-with-branches/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/rafaelapb/.nvm/versions/node/v14.19.1/bin/node" "/Users/rafaelapb/Projects/cactus-with-branches/node_modules/indy-sdk/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/rafaelapb/Projects/cactus-with-branches/node_modules/indy-sdk

**Comment by outSH** [comment]
@RafaelAPB There was an update in `BUILD.md` some time ago that includes step for installing Indy SDK - https://github.com/hyperledger/cactus/blob/main/BUILD.md?plain=1#L108

Requiring libindy only to build packages using npm indy-sdk is suboptimal, but this is outside of our scope I'm afraid. Currently I don't see other way around if we want to support indy ledgers :(

**Comment by petermetz** [comment]
Closing this as fixed implicitly by a PR that makes the indy install optional (the configure script no longer requires it by default)
