### ISSUE TITLE
Multi-request for federation leader

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger/cactus#22]
Add ability to queue requests for federation leader, considering the distributed nature e.g. if leader drops then can't lose queue

**Comment by jonathan-m-hamilton** [comment]
@hugo-borne  to provide additional details for @petermetz  to define approach / blueprint

**Comment by hugo-borne** [comment]
"Multisig" object is instantiated here for the first time: 
https://github.com/hyperledger-labs/blockchain-integration-framework/blob/be6c39c009812416fbd619ea2a32062b7e9b9cd3/src/Validator.js#L73
We want to replace this line with logic that instantiates a new "Multisig" object and put it in a queue each time a new request comes in

Each time we need to update a "Multisig" object, we need to identify which request we are targeting and update the good "Multisig" object in the queue:
https://github.com/hyperledger-labs/blockchain-integration-framework/blob/be6c39c009812416fbd619ea2a32062b7e9b9cd3/src/Validator.js#L239
https://github.com/hyperledger-labs/blockchain-integration-framework/blob/be6c39c009812416fbd619ea2a32062b7e9b9cd3/src/federation-communication.js#L75
https://github.com/hyperledger-labs/blockchain-integration-framework/blob/be6c39c009812416fbd619ea2a32062b7e9b9cd3/src/federation-communication.js#L181

We need to add a "release" step when the result is given back to the requester to remove the associated "Multisig" object from the queue

**Comment by petermetz** [comment]
Superseded by #123  and the stateless API server design where we did away with leader elections completely. Effectively, with the new architecture the queuing happens on the TCP level and is performed by the load balance or reverse proxy (or both) as they are responsible for not dropping incoming requests and to phase out unhealthy API server nodes (in the case of load balancers).
