### ISSUE TITLE
docs: automated web publishing and free text search

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger/cactus#221]
### Description
As a user or contributor of Hyperledger Cactus, I would like documentation to be more accessible.  This includes searchability without having to sort through various code included on Github.  

### Acceptance Criteria
The Cactus Maintainers believe that http://readthedocs.io/ is best suited to achieve these goals through source driven documentation.  RtD is popular with other Hyperledger projects and is free for OSS.  

The tasks are:
- [x] Bootstrap ReadTheDocs.io account for Cactus. (https://readthedocs.org/projects/hyperledger-cactus/)
- [x] Check the documentation on the readthedocs website to know how to work with this.
- [x] Organize the ./docs/ folder/sub-folders/files to provide a logical layout for the ReadTheDocs website
- [ ] Include the information of the README files of the plugins.
- [x] (#157) Include the whitepaper on the ReadTheDocs website in both HTML and PDF versions

**Comment by petermetz** [comment]
Bootstrapped an instance of ReadTheDocs.io for us, now we just need to refactor the documentation to somewhat conform to the format that makes sense (the menu items on the documentation webpage are derived directly from the file names of the markdown files)

**Comment by sfuji822** [comment]
Can we collaborate on making guidelines for documentation as well?
I believe Sphinx requires special notation at coding, and guidelines may help to avoid generating errors in the process.

**Comment by petermetz** [comment]
@sfuji822 Sounds good to me! Full disclosure: I don't know much about Sphinx.
