### ISSUE TITLE
feat(consortium): bootstrap

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#224]
### Description

As an aspiring Cactus consortium member/operator I want to be able to bootstrap a consortium with minimal effort (pre-shared public keys) so that I can build consortium(s) where separate members can run their own Cactus nodes as part of the consortium and have it all work together in order to achieve my desired outcomes with the software (one or more of the use cases of Cactus).

### Acceptance Criteria
1. Bootstrapping can be done by any of the member nodes
2. Bootstrapping takes as input the initial set of network hosts and public keys (DNS or IP)
3. Auto-discovery features to be kept in mind even if not outright implemented here
4. Avoid central storage being necessary on any level, but be flexible enough for future use of threshold cryptography/multi-sig data storage smart contracts for more sophisticated consortium management options.
5. Don't roll your own DLT. Remember: Cactus is distributed software, but not a ledger.

**Comment by sfuji822** [comment]
Do you mean you are adding features on existing one ?
I contributed related work at https://github.com/hyperledger/cactus/blob/master/whitepaper/whitepaper.md#422-bootstrapping-cactus-application .
My team is working on implementing the part of bootstrapping of business logic plugin as exampled application (fabcar-trade), which will be posted as PR near future.
I would like to discuss further details based on existing texts.

@petermetz  @jonathan-m-hamilton @takeutak

**Comment by petermetz** [comment]
> Do you mean you are adding features on existing one ?
> I contributed related work at https://github.com/hyperledger/cactus/blob/master/whitepaper/whitepaper.md#422-bootstrapping-cactus-application .

I would say no, because this is not for bootstrapping the application, but the consortium itself so what you describe in https://github.com/hyperledger/cactus/blob/master/whitepaper/whitepaper.md#422-bootstrapping-cactus-application is complementing the consortium bootstrap, they are not really in conflict as far as I can tell.

> My team is working on implementing the part of bootstrapping of business logic plugin as exampled application (fabcar-trade), which will be posted as PR near future.
> I would like to discuss further details based on existing texts.

@sfuji822 I meant basically what's in the `plugin-consortium-manual` package in the PR #242 specifically what the whitepaper section of that PR shows with the sequence diagram. Happy to discuss further as well.

**Comment by petermetz** [comment]
Closing as this was fixed by #242
