### ISSUE TITLE
Error when sharing keys

### ISSUE THREAD

**Issue by lucianoacsilva** [hyperledger/cactus#226]
Hello,

Trying here to share the public keys of the platform with **npm run scenario:share**, but get this error: 

`
 Error: validator is not alive
`

Someone knows what could the reason be?

**NOTE:** Trying to run the scenarios only with **Fabric** and **Quorum** environments, since my machine does not support the **Corda** environment performance requirements (which are very heavy).

**Comment by petermetz** [comment]
https://github.com/hyperledger/cactus/issues/208#issuecomment-662177104
