### ISSUE TITLE
feat(examples): Cactus examples

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#232]
**Is your feature request related to a problem? Please describe.**
Cactus users cannot understand how to use Cactus if there is without useful examples.

**Describe the solution you'd like**
We can provide examples for Cactus users.

**Comment by petermetz** [comment]
@takeutak I recommend classifying it with `docs` instead of `feat`. The `feat` stands for `feature` and is meant for commits that add a new feature to the software in the source code. What do you think?

**Comment by takeutak** [comment]
Sorry, I mistook to make this issue as you said.  Moreover, the issue #181 includes the demo app.
Then I closed this issue at once.
