### ISSUE TITLE
docs(whitepaper): improve related work

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cactus#236]
**Description**
As a contributor/maintainer/developer I want to have specific information about the related work on the blockchain interoperability space. At this moment, the whitepaper provides little insights on what is happening on other projects.

**Acceptance Criteria**
The whitepaper exposes different approaches to the blockchain interoperability problem, and how Cactus relates to them

cc @petermetz @jonathan-m-hamilton @takeutak @sfuji822

**Comment by dilumb** [comment]
If relevant, we cover lots of blockchain migration patterns & scenarios in use at [https://arxiv.org/abs/1906.00239](url)

**Comment by RafaelAPB** [comment]
@dilumb it looks appropriate. Feel free to add it to the related work!
