### ISSUE TITLE
Error when i launch the CI script

### ISSUE THREAD

**Issue by AlmaPenna** [hyperledger/cactus#239]
Hello,

I follow the build.md guide (https://github.com/hyperledger/cactus/blob/master/BUILD.md) and i have this error in terminal when i launch the **ci** script in the **tools** directory and i don't know how to fix:

![1](https://user-images.githubusercontent.com/17595885/88454041-bcf23080-ce6c-11ea-8887-a34e8fffaa06.png)

The log file:
[2020-07-25T09_33_57_595Z-debug.log](https://github.com/hyperledger/cactus/files/4975327/2020-07-25T09_33_57_595Z-debug.log)

Thanks

**Comment by AlmaPenna** [comment]
My versions:
- linux lite 4.8
- g++,gcc: 9.3
- node: v14.6.0
- npm: 6.14.6
- docker: 19.03.8

**Comment by petermetz** [comment]
@AlmaPenna Looking at the logs[1] you attached it looks to me that you are running NodeJS 8, not 14. Can you try with 12 or 14?

[1]
`EventEmitter.<anonymous> (/home/alma/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)`

**Comment by AlmaPenna** [comment]
@petermetz thanks! The problem was that for some reason my machine used nodejs 8 instead nodejs 14.
I remove all and reistall from the beginning and all works!
