### ISSUE TITLE
build: upgrade to Typescript 4.x

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#241]
### Description

As a contributor I want to be able to use the variadic tuple types feature of the compiler so that application developers who use the project can get the best developer experience when using the SDK for example.

The above example is not just a generic one, there is a specific point in the source code at present where the variadic tuple types would be great: The ApiClient class of the SDK package (`./packages/cactus-sdk`) has a method dedicated to extending the API client object with other API clients (the `DefaultApi` classes generated by the `typescrit-axios` profile of the OpenAPI generator tool)

Feature announcement: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#variadic-tuple-types

### Acceptance Criteria
1. Upgrade the compiler everywhere in the project
2. Tests are passing of course
3. There's no massive refactoring necessary for the change to happen (if it has to be done then open separate issues about those and tackle them prior to even attempting the upgrade)
4. Wait for the 4.0 *stable* version to come out first. It is possible that currently it is still in beta, but that is expected to change very soon if the past release cycles of Typescript are to be considered clues in that regard.

cc: @jonathan-m-hamilton @takeutak @sfuji822

**Comment by sfuji822** [comment]
Since our project is in mere developing stage.
I can accept your suggestion, but I doubt on technical needs in priority prospective.

**Comment by petermetz** [comment]
> Since our project is in mere developing stage.
> I can accept your suggestion, but I doubt on technical needs in priority prospective.

Agreed 100%, this is definitely medium priority at best, but more like low priority.
