### ISSUE TITLE
feat(common): KeyConverter class to and from PEM/hex/buffer 

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#247]
### Description
As a programmer I want to have a utility class in the common package (which is cross platform) that can convert back and forth between a raw byte stream, a hex string and PEM formatted public/private keys so that it's easier to work with these cryptographic primitives when developing new, higher level functionality.

### Acceptance Criteria
1. Cover all directions/permutations among the three mentioned formats
2. Test coverage both in NodeJS and browser (write the tests with tape)

**Comment by suyukuoacn** [comment]
Peter, I will work on this feature.

**Comment by petermetz** [comment]
Fixed by #255, closing
