### ISSUE TITLE
docs(whitepaper): clarify fluid node roles defined by plugins

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#249]
### Description
As a prospective user/operator of Cactus I want to have a clear vision on what is a validator node, a validator plugin, API server, Cactus node in general etc. so that I'm not overly confused about these terms used in the whitepaper and other parts of the documentation.

Questions about this have come up in the contributor's call/rocket chat a few times so I though it best to create a dedicated task for documentation where we explain the relationship between these pieces of the puzzle and focus on the bottom line that there is a shell that we call Cactus Node (the API server package contains the code for it) and depending on the plugins installed that Cactus node can be a validator node (if you use the validator plugin in it).

The originating meeting notes/recording is here: https://wiki.hyperledger.org/display/cactus/2020-08-06+Meeting+notes

### Acceptance Criteria
1. Update all relevant sections of the whitepaper and other documents as well
2. Make sure to provide graphical examples that are as simple as possible and demonstrate the different scenarios where the topology is spread out (like there's just one plugin running in each node and there's a bunch of nodes) and there's an example where a single node is doing everything with all the plugins in one place

cc: @takeutak @jonathan-m-hamilton @sfuji822 @RafaelAPB @cliveb

**Comment by RafaelAPB** [comment]
Agreed. This will be needed for the paper as well

**Comment by petermetz** [comment]
Breaking this issue into two as well to separate the two concerns that initially got mashed up together:
1. Cactus Node vs. API Server definitions
2. What makes a node a Validator/Attestator node (just having plugins like that installed on the node, that's all).

**Comment by RafaelAPB** [comment]
Regarding 1), I think you've done a great job defining that.
Regarding 2) I don't think we reached a consensus yet - I'll try to address that in the next meeting

**Comment by petermetz** [comment]
> Regarding 1), I think you've done a great job defining that.

Thank you very much :+1: 

> Regarding 2) I don't think we reached a consensus yet - I'll try to address that in the next meeting

I agree, 100% and thank you in advance! 
No rush with it, there's a separate issue for it now so we can track it there going forward (#336)

**Comment by petermetz** [comment]
Review is taking longer than expected, moving this to `v0.3`
