### ISSUE TITLE
feat(plugin-validator-besu): generate signature of simple asset

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#256]
### Description
As a developer I want to be able to obtain signatures of ledger state from Cactus nodes through the API so that I can implement federated validation in the new architecture as it was featured in the older codebase.

The end to end flow is this:

Client device with Cactus SDK => HTTP Request to Cactus Node (API Server with validator plugin) => validator plugin => besu ledger => smart contract method execution => return response (signature) to validator plugin => respond to HTTP request to the SDK

The above could also be called as an RPC interface where the validator plugin is just an RPC forwarder that converts REST API requests from the SDK to smart contract method invocations.

Related to:

Also feeds back into these
https://github.com/hyperledger/cactus/issues/99
https://github.com/hyperledger/cactus/issues/23

Old Simple Asset Transfer code (which is what we are improving here): 
https://github.com/hyperledger/cactus/tree/master/contribs/Accenture-BIF/core/examples/simple-asset-transfer

On-ledger verify method in the existing contract: https://github.com/hyperledger/cactus/blob/master/contribs/Accenture-BIF/core/examples/simple-asset-transfer/besu/contracts/Root.sol#L116

### Acceptance Criteria
1. Validation request can be sent via the SDK
2. The validator plugin has the ability to query ledger state by depending on (importing via the plugin registry) the ledger connector plugin
3. The validator plugin ships with it's own smart contract written in solidity that is able to perform the signature generation on-ledger. The smart contract can be the same or similar as the one linked above.
4. Individual nodes can be asked for their signatures separately
5. end to end test case where the `end to end flow` (see above) is actually played out with a besu test ledger running in a container
6. Validator plugin has a method that when called, it can deploy it's contract to the target ledger which can also leverage the ledger connector plugin which already knows how to deploy a JSON artifact of a compiled solidity contract.
7. OpenAPI specification file for the REST API endpoints that the plugin has

cc: @takeutak @jonathan-m-hamilton @sfuji822

**Comment by RafaelAPB** [comment]
I partially started tackling this issue while developing the blockchain migrator #158 (as I need to interact with smart contracts from within the test ledger). In particular, I've added methods to the besu-connector.

**Comment by petermetz** [comment]
> I partially started tackling this issue while developing the blockchain migrator #158 (as I need to interact with smart contracts from within the test ledger). In particular, I've added methods to the besu-connector.

@RafaelAPB Maybe this would also be helpful? https://github.com/hyperledger/cactus/pull/282
