### ISSUE TITLE
refactor: OpenAPI spec endpoint paths,verbs to come from endpoint class

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#269]
### Edit 1

Update: Thought more about this and would actually like to flip it so that the endpoint paths and verbs come from the endpoint classes themselves and get added to the open API spec Typescript file via those imports.

This has the downside of the open API spec TS file not being completely independent, but we can manage that once webpack 5 is out with the dependOn feature for entry points.

### Description
As a software engineer I want to have plugin endpoints whose HTTP paths are as easy to maintain as possible so that everyone on the project is more productive and a lower number of bugs slip through the cracks leading to higher software quality in general.

The current implementation pattern consists of having to define the path in two separate places in the code which of course leads to mistakes where one location gets updated and the other doesn't.
Instead of feeding the path to the endpoint class' constructor "manually" we should have a way to just look the path up directly in the open-API spec so that it drives the path from a single source of truth and thus making this type of mistake impossible.

Edit 1: The exact same kind of mistake can happen for the verb as well so make this apply to the HTTP verb used by the endpoint as well, not just the path.

### Acceptance Criteria
1. Solution should be simple
2. Need to avoid having to define the path in more than one place
3. There's no ambiguity between the endpoints that could cause the lookup to return the wrong endpoint path from the open API spec (maybe add a custom parameter to the open API spec that acts as an ID?)

cc: @takeutak @sfuji822 @jonathan-m-hamilton

**Comment by petermetz** [comment]
Update: Thought more about this and would actually like to flip it so that the endpoint paths and verbs come from the endpoint classes themselves and get added to the open API spec Typescript file via those imports.

This has the downside of the open API spec TS file not being completely independent, but we can manage that once webpack 5 is out with the `dependOn` feature for entry points.

**Comment by AzaharaC** [comment]
Working on this.
