### ISSUE TITLE
[Documentation] Links are broken

### ISSUE THREAD

**Issue by pratikpc** [hyperledger/cactus#286]
**Describe the bug**

Links in https://github.com/hyperledger/cactus/blob/master/docs/tutorials/simple-asset-transfer.md are broken

Specifically Link to Main Docs https://github.com/hyperledger/cactus/blob/master/docs/main/index.hmtl

And configure.sh

I found the link to simple-asset-transfer from https://www.hyperledger.org/blog/2019/11/20/accenture-open-sources-blockchain-integration-framework-as-a-hyperledger-lab

**Comment by petermetz** [comment]
Thank you for the report @pratikpc we definitely need to fix these

**Comment by petermetz** [comment]
Since last week we had the old example code removed so it makes sense to just delete the whole `./docs/tutorials/` folder altogether to temporarily solve this issue and then refer people to track #189 for the real fix which happens on a separate work stream.

**Comment by pret-a-porter** [comment]
@petermetz done
