### ISSUE TITLE
ci(ledger-connector): pilot light performance benchmarks

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#295]
### Description
As a maintainer I want to get an automated warning if a PR passes the tests, but has an adverse impact on performance as measured by a set of baseline benchmarks so that if a PR looks good to me, but in fact reduces performance to a 10th of what it used to be because of some mistake hidden in the code, then I am made aware of this as soon as possible (which hopefully makes it much easier to keep the code performant)

### Acceptance Criteria
1. Performance checks are part of the CI tests and the reports are easily accessible/readable (from the CI logs?)
2. The performance checks can be executed on the average developer machine and does not require/depend on external infrastructure to be set up (ideally docker should be the only dependency)

**Comment by petermetz** [comment]
FYI: https://www.npmjs.com/package/loadtest

**Comment by travis-payne** [comment]
I'll have a look at this

**Comment by kikoncuo** [comment]
Talk with Hyperledger Caliper 
Mark Wagner
Performance and Scale working group

**Comment by travis-payne** [comment]
https://github.com/hyperledger/cactus/pull/845
