### ISSUE TITLE
docs(readme): status badges for build, docs, license, etc.

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#306]
### Description
As a prospective user of Cactus I want to have instant and visual feedback on the project's baseline health metrics via badges so that I feel better about spending my time getting to know what Cactus is about, how it works and what/when/how could I contribute to the community.

See https://github.com/dwyl/repo-badges

### Acceptance Criteria
1. Badges are added on top of the readme file

cc: @jonathan-m-hamilton @sfuji822 @takeutak

**Comment by beckettnormington** [comment]
@petermetz, can you assign me this? Also, which badges would you like me to add to the README? I'll probably add the basic statistics, and you can give me feedback.

**Comment by jonathan-m-hamilton** [comment]
Thanks @beckettnormington ! Can you tackle License, CII Best Practices & Build Status?  Please ping if issues or other suggestions.  Thanks again for your contribution.

**Comment by beckettnormington** [comment]
@jonathan-m-hamilton, sure thing! I'll let you know if I experience any problems.

**Comment by beckettnormington** [comment]
@jonathan-m-hamilton, for Build Status, which tool are you using specifically? (e.g. Github Workflow, Github Pipeline, etc.)

**Comment by beckettnormington** [comment]
@jonathan-m-hamilton, PR created. Added an extra 'issues' badge as well to help keep things in order.
