### ISSUE TITLE
test(common): increase test coverage

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#309]
### Description
As a community member of Cactus I want to feel good about using software that has good test coverage so that I can sleep a little bit better (not much because severe bugs can still lurk in codebases with 100% test coverage, but nevertheless...)

Currently if you run the test command for the common package (see below) then you get a coverage report is is mostly in the red. The idea for this issue is to turn that green.

Execute the tests of the common package
```sh
npx tap --jobs=1 --timeout=60 "packages/cactus-common/src/test/typescript/{unit,integration}/"
```

The report at the end of the test execution:
```sh
Suites:   5 passed, 5 of 5 completed
Asserts:  47 passed, of 47
Time:     10s
--------------------------|----------|----------|----------|----------|-------------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------|----------|----------|----------|----------|-------------------|
All files                 |    82.51 |    67.61 |       50 |    82.35 |                   |
 main/typescript          |    86.01 |    72.88 |    52.94 |    86.15 |                   |
  bools.ts                |       50 |        0 |        0 |       50 |                13 |
  checks.ts               |       40 |        0 |        0 |       40 |          16,17,18 |
  coded-error.ts          |       20 |        0 |        0 |       25 |            7,8,12 |
  js-object-signer.ts     |    96.77 |    91.67 |      100 |    96.77 |                34 |
  key-converter.ts        |      100 |    96.15 |      100 |      100 |                83 |
  objects.ts              |     62.5 |    77.78 |       50 |    66.67 |    57,58,59,60,63 |
  public-api.ts           |      100 |      100 |    36.36 |      100 |                   |
  secp256k1-keys.ts       |      100 |      100 |      100 |      100 |                   |
  strings.ts              |    28.57 |        0 |        0 |    28.57 |     9,13,17,18,19 |
 main/typescript/logging  |     69.7 |    41.67 |    42.86 |     69.7 |                   |
  logger-provider.ts      |    71.43 |    42.86 |    33.33 |    71.43 |       26,27,28,29 |
  logger.ts               |    68.42 |       40 |    45.45 |    68.42 | 46,50,54,58,61,67 |
 test/typescript/fixtures |    71.43 |      100 |       50 |    71.43 |                   |
  dummy-classes.ts        |    71.43 |      100 |       50 |    71.43 |             11,24 |
--------------------------|----------|----------|----------|----------|-------------------|
```

### Acceptance Criteria
1. The first line (`All files`) is all green meaning that it's above threshold (I think the limit for green is 85% but not a 100% sure on that)
2. Tests added use the `tape` library (not `tap`)
3. Tests added follow the existing conventions

cc: @jonathan-m-hamilton

**Comment by eLeontev** [comment]
@petermetz what is the reason to use tape/tap instead of common used jest? Looks like tape does not support from the box a lot of required functionality (beforeEach/spies/flexible matchers, etc). 
Are you ok to add tests for common on jest?

**Comment by gabrielsoaresm94** [comment]
@petermetz  I'm trying to do the task with the documentation I found on github and also based on the tests that have already been created, everything ok?

* https://github.com/substack/tape
* https://ci.testling.com/guide/tape

**Comment by petermetz** [comment]
> @petermetz what is the reason to use tape/tap instead of common used jest? Looks like tape does not support from the box a lot of required functionality (beforeEach/spies/flexible matchers, etc).
> Are you ok to add tests for common on jest?

@eLeontev Would strongly prefer to keep it tape, but happy to hear more about what Jest could bring to the table. The rationale behind tape is to have support for the [Test Anything Protocol](http://testanything.org/) and in general to have tests and a testing framework that is simple and lightweight even if some of the cool features are missing. Does Jest support TAP? 

P.S.: The reason we have both tap and tape is because we are in the middle of a slow, gradual migration from tap to tape because only tape supports running tests in browsers.

**Comment by petermetz** [comment]
> @petermetz I'm trying to do the task with the documentation I found on github and also based on the tests that have already been created, everything ok?
> 
>     * https://github.com/substack/tape
> 
>     * https://ci.testling.com/guide/tape

@gabrielsoaresm94 Yeah sounds good. Just make sure you and @eLeontev are aligned and not working on the same thing in parallel. ;-)

**Comment by gabrielsoaresm94** [comment]
I managed to create some unit tests, but I have a problem to test the Logger, since its methods return void. I was able to instantiate the class to call the method and see the log appear, but not pass the test yet. Any tips on how to use the `tape` to listen to a function?

**Comment by petermetz** [comment]
> I managed to create some unit tests, but I have a problem to test the Logger, since its methods return void. I was able to instantiate the class to call the method and see the log appear, but not pass the test yet. Any tips on how to use the `tape` to listen to a function?

@gabrielsoaresm94 Awesome, thank you for all your efforts so far!
I've never done this myself either, but I can definitely recommend that you take a look at this specific part of the NodeJS documentation where they talk about process std out/err and console.log/error working:
https://nodejs.org/api/process.html#process_process_stdout

Based on what's described on the above link, this is just made up pseudo-ish code I can imagine being a workable solution blueprint. Let me know if this is good enough guidance!

logger.test.ts

```typescript
// import dependencies...
test("logger writes to stdout", async(t: Test) => {

const log = LoggerProvider.getOrCreate({ level: "TRACE", label: "logger-test" });

// generate random UUID v4 to guarantee we don't mistake something else as the marker
const marker = uuidv4();

// hook up to the stdout data stream and wrap it in a promise that can be awaited 
// for when the marker does appear on stdout (which would be a passing test)
// or when it times out (which would mean the test is failing).
// Certain issues could happen here if the stream is chunking data and then you never
// actually get the complete marker string at once but instead different parts of it
// but I did not consider this because the uuid is only a few dozen bytes when stored as a hex string 
// so I'm pretty confident it wouldn't get chunked (probably not impossible either though so
// if you are paranoid about that happening (which would make the test flaky) then you can
// bake in some stream data aggregation instead where you collect and continually append
// the incoming data chunks and test for marker presence in the aggregate variable not the chunk
// that is provided in the 'data' event handler callback.
  const promise = new Promise((resolve, reject) => {
     const timerId = setTimeout(() => reject(new Error('Timed out waiting for marker to appear on stdout')));
     process.stdout.on('data', (data: Buffer) => {
        if (data.toString('utf-8').includes(marker)) {
        clearInterval(timerId);
         resolve(marker);
         }
    });
});

// send the log now that we have hooked into the stream waiting for the marker to appear
log.info(marker);

// wait for the marker to appear on stdout OR crash with timeout if it never comes
await promise; 
});

// rinse and repeat for stderr
test("logger writes to stderr", ...)

```

**Comment by petermetz** [comment]
@gabrielsoaresm94 Are you still planning on submit the PR?

**Comment by gabrielsoaresm94** [comment]
@petermetz  as I couldn't finish on time, I decided not to send any pr yet, I hope to be able to finish everything even with the event already over. I read about process.stdout and tested the code but it didn't work, I'm currently reading this article:

https://dev.to/gajus/capturing-stdout-stderr-in-node-js-using-domain-module-146a

**Comment by petermetz** [comment]
> @petermetz as I couldn't finish on time, I decided not to send any pr yet, I hope to be able to finish everything even with the event already over. I read about process.stdout and tested the code but it didn't work, I'm currently reading this article:
> 
> https://dev.to/gajus/capturing-stdout-stderr-in-node-js-using-domain-module-146a

@gabrielsoaresm94 Very much appreciated, thank you for your persistence! I'm happy to work together on it with you if you send a link to your fork's branch that you are working on (then I can double check if my recommended approach above works at all or was it a mirage :-) ).

**Comment by gabrielsoaresm94** [comment]
@petermetz thanks for the help: https://github.com/gabrielsoaresm94/cactus

**Comment by petermetz** [comment]
> @petermetz thanks for the help: https://github.com/gabrielsoaresm94/cactus

@gabrielsoaresm94 Do you have the latest state pushed? I can't see any files in there with the logger tests on your branch.

**Comment by gabrielsoaresm94** [comment]
@petermetz  I'm sorry, I improved the organization and put the logger tests inside `/unit/logging/logger.ts`. I also added the file `test-process.js`, to be able to test the `process.stdout`. The captureStdout function was able to read the terminal logs, but I was unsuccessful when trying to pass for typescript. I will reread and study this article more to be able to adapt it better.

**Comment by petermetz** [comment]
> @petermetz I'm sorry, I improved the organization and put the logger tests inside `/unit/logging/logger.ts`. I also added the file `test-process.js`, to be able to test the `process.stdout`. The captureStdout function was able to read the terminal logs, but I was unsuccessful when trying to pass for typescript. I will reread and study this article more to be able to adapt it better.

@gabrielsoaresm94 No worries at all! I checked it out and made a bunch of changes to fix it up and also concluded that the logger testing idea that I explained above just does not work because the log messages do not get emitted by the stdout stream for some reason. So I'm totally fine with skipping the tests for the logger for now, the rest of it looks more or less okay with a few nits like using the `uuid` library instead of `uuidv4` and then import the v4 function like this: `import { v4 as uuidv4 } from "uuid";`.

I tried to force push my changes onto your branch but I do not have write permission on your Cactus fork. If you can make me a contributor there then I should be able to do it and then you could just fix the deprecation warning mentioned above and submit the actual PR to the upstream Cactus repo for review by all the maintainers.

**Comment by gabrielsoaresm94** [comment]
> > @petermetz I'm sorry, I improved the organization and put the logger tests inside `/unit/logging/logger.ts`. I also added the file `test-process.js`, to be able to test the `process.stdout`. The captureStdout function was able to read the terminal logs, but I was unsuccessful when trying to pass for typescript. I will reread and study this article more to be able to adapt it better.
> 
> @gabrielsoaresm94 No worries at all! I checked it out and made a bunch of changes to fix it up and also concluded that the logger testing idea that I explained above just does not work because the log messages do not get emitted by the stdout stream for some reason. So I'm totally fine with skipping the tests for the logger for now, the rest of it looks more or less okay with a few nits like using the `uuid` library instead of `uuidv4` and then import the v4 function like this: `import { v4 as uuidv4 } from "uuid";`.
> 
> I tried to force push my changes onto your branch but I do not have write permission on your Cactus fork. If you can make me a contributor there then I should be able to do it and then you could just fix the deprecation warning mentioned above and submit the actual PR to the upstream Cactus repo for review by all the maintainers.

@petermetz thanks for the help, i just invited you.

**Comment by petermetz** [comment]
> @petermetz thanks for the help, i just invited you.

@gabrielsoaresm94 Cool, I've just pushed onto your branch so you should be seeing the updates if you do a git pull with a rebase. Let me know how it goes, happy to provide more guidance if needed!

**Comment by gabrielsoaresm94** [comment]
Nice @petermetz thanks for the help , I saw your updates and realized that I learned more than contributed. I would like to help with the integration tests, but looking at the test that already existed `api-surface.ts` I saw it is very similar to what exists in the unit tests. Is there any pattern I could follow?

**Comment by petermetz** [comment]
> Nice @petermetz thanks for the help , I saw your updates and realized that I learned more than contributed. 

@gabrielsoaresm94 You are welcome!

> I would like to help with the integration tests, but looking at the test that already existed `api-surface.ts` I saw it is very similar to what exists in the unit tests. Is there any pattern I could follow?

@gabrielsoaresm94 For the scope of this GH issue we don't need integration tests because `common` is a leaf package so there isn't any dependencies on other packages (by design) where integration with other components should be verified. 
Sorry if this wasn't clear from the original description. :-)

**Comment by gabrielsoaresm94** [comment]
@petermetz Got it, all right then. It was good to work with you, thanks for the opportunity. I just need to do PR?

**Comment by petermetz** [comment]
> @petermetz Got it, all right then. It was good to work with you, thanks for the opportunity. I just need to do PR?

@gabrielsoaresm94  Depends, have you addressed this? =>

> So I'm totally fine with skipping the tests for the logger for now, the rest of it looks more or less okay with a few nits like using the uuid library instead of uuidv4 and then import the v4 function like this: import { v4 as uuidv4 } from "uuid";.

**Comment by gabrielsoaresm94** [comment]
> @gabrielsoaresm94 Depends, have you addressed this? =>
> 
> > So I'm totally fine with skipping the tests for the logger for now, the rest of it looks more or less okay with a few nits like using the uuid library instead of uuidv4 and then import the v4 function like this: import { v4 as uuidv4 } from "uuid";.

Done, I accepted the corrections and changed the package to `uuid`, I will do a pr. Thanks for all the help and sorry for the delay.

**Comment by petermetz** [comment]
> Done, I accepted the corrections and changed the package to `uuid`, I will do a pr. Thanks for all the help and sorry for the delay.

@gabrielsoaresm94 No problem at all. Thank **you** for the contribution! Looking forward to the PR!
