### ISSUE TITLE
docs: whitepaper terminology

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cactus#310]
**Is your feature request related to a problem? Please describe.**
The terminology employed at the whitepaper is ad-hoc, and creates semantic barriers not only on the whitepaper, but also on its materialization (i.e., code)

**Describe the solution you'd like**
A clear and concise description of the terminology, for example, following NIST 8202's terminology section.

**Describe alternatives you've considered**
Leave the current terminology as is.

**Comment by petermetz** [comment]
Related: #249

**Comment by RafaelAPB** [comment]
Being discussed in the academic paper efforts. Closing for now.
