### ISSUE TITLE
refactor(sdk): rename sdk package to api-client

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#314]
### Description
As a developer I want to be able to quickly scan the packages available in the git repo so that I can get a better understanding of the architecture in a shorter time.

Currently we have a package named `cactus-sdk` which is probably ambiguous with the project itself which we sometimes refer to as `an SDK of SDKs`. That ambiguity could cause rational minds to question our terminology (yet again) since if the whole project is `the` SDK then why do we have 10+ packages and only one of them called SDK.
Based on all this that we should rename the package from `@hyperledger/cactus-sdk` to `@hyperledger/cactus-api-client` which much better describes (narrower scope) what that package actually does.

### Acceptance Criteria
1. In the `package.json` file, the properties: name, main, browser, browserMinified, mainMinified properties are all updated
2. The references in all the other packages are also updated to import the new package instead of the old one (e.g. project must compile without issues
3. Documentation is updated where necessary (the readme.md file of the package needs a looksie for sure)

cc: @RafaelAPB @sfuji822 @jonathan-m-hamilton @takeutak

**Comment by yash2189** [comment]
Hello I'm new to opensource. I went through the packages file and was able to find the file package named `cactus-sdk`. Does that need to be renamed as `cactus-api-client`?

**Comment by petermetz** [comment]
> Hello I'm new to opensource. I went through the packages file and was able to find the file package named `cactus-sdk`. Does that need to be renamed as `cactus-api-client`?

@yash2189 Yes, among a few other things that's one of the items to take care of in the scope of this issue! 
If you are also new to NodeJS, monorepos, Lerna, etc I recommend taking a look at these resources as well (will make much more sense after being familiar with the concepts):

https://docs.npmjs.com/packages-and-modules/
https://blog.npmjs.org/post/186494959890/monorepos-and-npm
https://github.com/lerna/lerna
Also potentially this if you are also new to Typescript: https://www.typescriptlang.org/

**Comment by yash2189** [comment]
Thanks @petermetz yes I do not have much experience with typescript , Nodejs , lerna. I'll surely visit the resources provided.

**Comment by petermetz** [comment]
> Thanks @petermetz yes I do not have much experience with typescript , Nodejs , lerna. I'll surely visit the resources provided.

No worries @yash2189 another resource I can recommend is the local documentation in the `CONTRIBUTING.md` file and the `BUILD.md` file in this repo's root folder. Plenty of useful explanation in both of those if you are a new to some concepts. It will also help you ensure that if you do submit a pull request it will be one that is easier to review/accept/merge. Thank you in advance!

**Comment by yash2189** [comment]
@petermetz  I had a look on the resources that you provided.I have a question ....After the package has been renamed do we have to run the `npm` command again in order to generate new files which would replace the old ones?

**Comment by petermetz** [comment]
> @petermetz I had a look on the resources of `npm` that you provided.I have a question...After the package has been renamed do we have to run the `npm` command again in order to generate new files which would replace the old ones?

@yash2189 Yes, that's necessary to make sure your contribution works as expected. Safest to run the full CI suite, but if you don't want to do that it's okay to let Travis CI do it once you support the PR.

**Comment by yash2189** [comment]
@petermetz I have renamed the package and updated the required documentation. Raising a PR for the same. Please review it.

**Comment by yash2189** [comment]
@petermetz I have renamed the package and updated the required documentation. Raised a PR  #314 for the same. Please review it.
Thanks.

**Comment by petermetz** [comment]
> @petermetz I have renamed the package and updated the required documentation. Raised a PR #314 for the same. Please review it.
> Thanks.

Great! Thank you so much @yash2189
