### ISSUE TITLE
docs(architecture): delete the current validator folder

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#329]
### Description
As a person interested in leraning about Cactus I want to have documentation that is not out of date so that I'm not wasting my time reading materials that will not actually help me get ahead.

Currently the `./docs/architecture/validator/` folder only contains another folder (`./docs/architecture/validator/leader-election`) which has outdated information since we no longer have leader elections (as part of our push to have stateless API servers for horizontal scalability).

Also in general the readthedocs page of ours should be better organized which this will help with.

### Acceptance Criteria
1. Delete the `./docs/architecture/validator` folder.

cc: @jonathan-m-hamilton @takeutak @sfuji822

**Comment by sheetalsingala** [comment]
Can I work on this?

**Comment by petermetz** [comment]
> Can I work on this?

Absolutely! Thank you for the PR @sheetalsingala ! (And sorry for not responding here earlier, I was processing notifications backwards so your PR came first)
