### ISSUE TITLE
docs(whitepaper): packages section to match v0.4.0 

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#343]
### Description

The whitepaper has a section that enumerates the proposed packages the project (Cactus) should have.
This has gotten slightly out of date over recent months as we progressed steadily towards the v0.2.0 release/milestone.

### Acceptance Criteria
1. Each currently (as of v0.4.0) existing package must have it's own section in the whitepaper with an explanation as to what it does.
2. From the above the following can be (but doesn't have to be) exempt: cactus-test-* packages and cactus-example-* packages.

cc: @sfuji822 @jonathan-m-hamilton @takeutak

**Comment by AzaharaC** [comment]
working on this.
