### ISSUE TITLE
feat(api-server): publish API server docker image

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#345]
### Description

Depends on https://github.com/hyperledger/cactus/issues/346

As a developer I want to be able to run a Cactus API server with arbitrary configuration by simply running a docker container of an image that is published and available to anyone on DockerHub so that I can deploy Cactus in a much wider range of environments that have native container support (example: Kubernetes).

### Acceptance Criteria
1. The complete API server configuration (consortium, all plugins, etc) can be customized through arguments of the container the same way as if the API server was being started directly on the host OS as a process.
2. `Dockerfile` is written which is also integrated with the DockerHub integration we have so that upon each commit to the main branch a new image is built and tagged the same way we already have it set up currently for the all-in-one images that help with testing.
3. Document naming conventions for container images (cactus prefix, all-in-one suffix for ledgers, package name )

cc: @takeutak @jonathan-m-hamilton @sfuji822

**Comment by petermetz** [comment]
95% of the work, especially the heavy lifting has been done for this in the scope of another issue  https://github.com/hyperledger/cactus/issues/344 so from here on the complexity on this one should be pretty low (knock on wood).

**Comment by kikoncuo** [comment]
Specify a naming convention for future docker images to be published
