### ISSUE TITLE
docs(examples): supply chain app WWW root config

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#347]
### Description

The supply chain app example configures its API server at the moment with a WWW path for the front-end that is hardcoded in the back-end package. This makes it inflexible and in certain situations will just break the example because the back-end will not serve the UI if the path is incorrect.

We need to have a way of passing in a CLI/ENV arg/variable with the WWW root path so that this can be remedied by the users regardless of how they choose to install/try out the example.

### Acceptance Criteria
1. The example back-end can serve the front-end assets regardless of what is the `current working directory` where it was started from.

cc: @sfuji822 @jonathan-m-hamilton @takeutak

**Comment by petermetz** [comment]
Update: this issue was made much lower priority since we containerized the entire example supply chain app so that this bug no longer happens as long as you are using the provided container image. 
It is still an issue if you want to build locally which is what people who actually want to contribute will have to do sooner or later so the bug still needs to be addressed, just not as urgently.

**Comment by jordigiam** [comment]
Working on this.
