### ISSUE TITLE
refactor(core-api): discontinue web service plugin aspect

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#350]
### Description

Adding [`WEB_SERVICE`](
https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/plugin-aspect.ts#L5) as a `PluginAspect` enumeration value was a mistake since it makes it possible for plugins to have multiple aspects, which was not the intention of plugin aspects at all.

Going forward, after the removal of `WEB_SERVICE` calling code can use the `isPluginWebService` method to determine which plugin exposes web services instead: https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts#L13

### Acceptance Criteria
1. Project still compiles and tests are passing.
2. PluginAspect enum no longer has `WEB_SERVICE` as a possible value.

cc: @jonathan-m-hamilton @takeutak @sfuji822

**Comment by TonyRowntree** [comment]
Issue may need re-estimating as I will need to first learn about the plugin aspect.

**Comment by petermetz** [comment]
> Issue may need re-estimating as I will need to first learn about the plugin aspect.

@TonyRowntree Sure thing! Grab me for a little code level intro tomorrow
