### ISSUE TITLE
refactor: discontinue dedicated HTTP listeners (ExpressJS apps) for web service plugins

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#358]
### Description

Originally we implemented this feature to provide the possibility for deployments to run plugins isolated on separate web domains/network hosts, but with today's code the latter can also be achieved by running multiple API servers which makes the dedicated HTTP listeners of plugins a redundant feature which also throws a wrench into the consortium definition powered routing within nodes.

Added benefit: Make it less confusing to implement plugins.

--- 

Examples of the code that is being talked about in this issue:

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts#L68

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts#L101

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts#L58

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts#L73
---

These shutdown methods on plugin classes could be deleted since this change would place the concern of HTTP listeners back completely to the control of the API server:
https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts#L45

--- 

Also could get rid of these from the common interface definition for web service plugins:

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts#L9

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts#L10

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts#L20

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts#L23

### Acceptance Criteria
1. Redundant code is removed
2. Updated the common web service plugin interface
3. Code compiles, tests are passing. Where applicable test cases were updated so that the HTTP layer isolation is demonstrated via separate instances of API servers rather than plugins running their dedicated listeners. 

cc: @sfuji822 @takeutak @jonathan-m-hamilton

**Comment by siv2r** [comment]
Hey, I am new to HL Cactus and would like to start contributing to this project. Can I try working on this issue?

**Comment by petermetz** [comment]
@siv2r Welcome to the project! Yeah,  I think this is a good one to get started on, it's mostly just demolition work (deleting code).
If you need any help I'm here and I can also recommend our pair programming sessions that run daily (check the wiki or the calendar for the links)

**Comment by TonyRowntree** [comment]
hey @siv2r are you still working on this? Or can I pick this up?

**Comment by siv2r** [comment]
Sure, you can take it up.

**Comment by TonyRowntree** [comment]
Also delete from the connector interface

**Comment by petermetz** [comment]
@TonyRowntree Is it cool if I reassign this to @Leeyoungone ?

**Comment by TonyRowntree** [comment]
> @TonyRowntree Is it cool if I reassign this to @Leeyoungone ?

Sure thing! 👍

**Comment by petermetz** [comment]
@Leeyoungone Please make a comment on the issue to enable assignment.

**Comment by Leeyoungone** [comment]
Thank you for letting me pick this us!
