### ISSUE TITLE
docs(examples): extend supply chain app with fabric specific elements

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#362]
### Description

Depends on #361, #360, #319 and #320 #347 

The supply chain app example should have a third ledger (Fabric) included that has a third smart contract on it that implements a shipment tracking feature for the existing example application where we can only register harvests but not actually track the shipments themselves.
The model should be updated so that bookshelves are referencing a shipment not a harvest and shipments reference a harvest so that the reference chain is complete from shelf to the lumberjack's chainsaw buzzing in the forest.

### Acceptance Criteria
1. Code compiles and tests are passing
2. The UI (`supply-chain-frontend` package) has a CRUD screen where one can add new shipments, associating them with harvests
2.1. Creating a shipment stores the data of said shipment on the contract's state in the Fabric ledger
3. The bookshelves and harvests CRUD screens is updated according to the model changes described above

cc: @sfuji822 @takeutak @jonathan-m-hamilton

**Comment by jordigiam** [comment]
Working on this.

**Comment by AzaharaC** [comment]
working on this.

**Comment by kikoncuo** [comment]
Check #361
