### ISSUE TITLE
feat(besu): define data ledger record locator model type

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#365]
**Is your feature request related to a problem? Please describe.**

Depends on: #364

There is no well defined scheme (OpenAPI spec types) in the besu connector plugin for referencing any piece of data on a besu ledger.

**Describe the solution you'd like**

Define a type called `BesuRecordLocator` in the `openapi-spec.ts` file of the besu connector that is capable of describing/uniquely identifying any piece of data (aka record) on a besu ledger so that we can then re-use this type across different endpoint definitions for the besu connector where it is needed.

1. The type defined should be aware of the existing consortium definition meaning that it is safe to assume that a `ledgerId` property will uniquely identify the ledger and encode enough information for the ledger to be reached via Cactus connector plugins or the API client.
2. The `BesuRecordLocator` type must be capable of referencing a particular piece of state **within** a contract
3. The `BesuRecordLocator` type must be capable of referencing a particular contract's `CALL`'s return data.

**Describe alternatives you've considered**

Been looking into what others have concluded on this topic so far (not a new problem) and there are some good schemes, but it would be best for us to support the consortium definition we have in-house already meaning that we do not need to store in the record locator the network host of a ledger for example, nor the credentials required to access it because all of that is taken care of in different components of the system: see the paragraph above.

**Additional context**

Consortium definition is about to be refactored as well => #349 

cc: @sfuji822 @takeutak @jonathan-m-hamilton

**Comment by AzaharaC** [comment]
For the moment we will leave out of this issue the part of adding the ```ledgerId``` property. The reason for this can be found in the comment below:
https://github.com/hyperledger/cactus/pull/1102#pullrequestreview-696703471
