### ISSUE TITLE
tools(fabric-aio): user defined Fabric Samples version

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#391]
**Is your feature request related to a problem? Please describe.**

Right now (as of #389 ) the Fabric AIO image uses DinD (Docker in Docker) and pulls up a complete "first-network" ledger, verbatim as provided by the [Fabric Samples repo](https://github.com/hyperledger/fabric-samples/tree/release-1.4/fabcar)
and the version the Fabric bootstrap script gets fed through the parameters is hardcoded as `v1.4.8` which is exactly what we want for the Fabric 1.x connector's development, but once we start with writing the connector (or updating the existing one for) Fabric 2.x we'll need the [Cactus Fabric AIO image](https://github.com/hyperledger/cactus/tree/master/tools/docker/fabric-all-in-one) to be able to pull up a Fabric 2.x ledger (most likely something closer to 2.2.x to be exact).

**Describe the solution you'd like**

1. The Dockerfile to have/specify an `ENV` variable for customizing the Fabric version that gets pulled at startup.
2. The `FabricTestLedger` class to have a constructor parameter that gets fed into the `ENV` variable mentioned in 1) 
3. Image can handle the differences between 1.x and 2.x Fabric Samples repo (I think they changed the directory structure and renamed some of them?)

**Describe alternatives you've considered**

Considered CLI and docker build arguments instead and also considered keeping the Fabric version hardcoded and publishing different versions of the AIO image that map their versions to the Fabric version they come equipped with.
These don't seem like bad ideas either, but I thought it best to start with the fully dynamic option, see how it works and then take it from there. 

**Additional context**

There's a PR open for upgrading the AIO image to support DinD: #389 

cc: @takeutak @sfuji822 @jonathan-m-hamilton

**Comment by jagpreetsinghsasan** [comment]
I am working on this issue.
