### ISSUE TITLE
docs(readme): video guide for initial project setup

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#413]
### Description
As a prospective contributor I want to be able to get my development environment set up as quickly as possible so that I don't get turned off by the chores involved in doing so and therefore I am more likely to stick around and help the community grow.

### Acceptance Criteria
1. Produce a video showing initial project setup from git clone to stepping through code with the VSCode debugger
2. Cover the `./.vscode/launch.json` template file
3. Update the README with a link to the video on one more widely used video sharing platform(s).
4. Share the script video to validate
5. Add video to Youtube platform
cc: @RafaelAPB @takeutak @sfuji822 @jonathan-m-hamilton

**Comment by jordigiam** [comment]
Working on this.
