### ISSUE TITLE
fix: test ledger image tag references to be exact

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#421]
**Describe the bug**

Currently the test ledger classes all default to `latest` as the default tag if unspecified via constructor options.
This is bad because whenever we have a change to any one of the images, there's this limbo and false negative (failing) CI runs if the new version of the image has some incompatibility (which they most of the time do). 

**To Reproduce**

Make a breaking change to an image, try to run the integration tests or have a PR that passes the CI and observe your own demise.

**Expected behavior**

Test ledger classes declare explicit/exact tag references associated with a specific SHA so that a given version of the code has stable test outcomes as long as the docker registry does not start disappearing image versions or changing them.

**Cloud provider or hardware configuration:**

Every environment suffers from this.

Every release suffers from this.
Currently on `v0.2.0`

**Hyperledger Cactus Plugins/Connectors Used**

Fabric is the notorious culprit because our image has issues there (and the fix is stuck in the review queue for now).

**Additional context**

This is a great example of why we need reproducible builds, which the docker containers are a part of.

cc: @takeutak @sfuji822 @jonathan-m-hamilton @jagpreetsinghsasan

**Comment by jordigiam** [comment]
Working on this.
