### ISSUE TITLE
style: implement HL DCI WG recommendations

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#424]
## Description

As a Cactus maintainer I want to make sure we are doing our part in making people feel included. The DCI WG has drafted some recommendations to the TSC and I figured we could get ahead of the curve on implementing this one below:

> Recommendation 2: Adopt inclusive terminology in coding standards
> Proposed ask #2: Can the Technical Steering Committee set guidelines for projects to follow around using inclusive language in both code and documentation and set expectations for when those changes should be made?  The DCIWG recommends...
> Example: Replace the terms "blacklist", "whitelist", "master" and "slave" in current and stable development branches of Hyperledger repositories.

Source: https://wiki.hyperledger.org/display/DCI/Turning+Recommendations+into+Proposed+Motions+for+the+GB+and+TSC

More context:
- Discusison on the DCI WG mailing list about a DCI linter that would automate checks for _Recommendation 2_ as quoted above.
https://lists.hyperledger.org/g/dci-wg/message/268
- We'll make an announcement about the default branch being renamed to `main` on the mailing list and Rocket Chat.

## Acceptance Criteria
1. Default branch has been renamed to `main` as we discussed during the Cactus maintainer's call on 2020-12-15.
2. Source code/documentation terminology updated accordingly where applicable

cc: @sfuji822 @takeutak @jonathan-m-hamilton @hartm

**Comment by cliveb** [comment]
Missed the calls. Is the new 'default branch' simply named 'default'..?

**Comment by petermetz** [comment]
> Missed the calls. Is the new 'default branch' simply named 'default'..?

@cliveb The plan is to have it called `main`, sorry for the misleading phrasing, I'll make some edits to make it clearer, it should've been clearly mentioned what the new branch name is going to be.

**Comment by petermetz** [comment]
Branch migration is done, closing as complete.
