### ISSUE TITLE
feat(core-api): define common consortium plugin interface

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#427]
**Is your feature request related to a problem? Please describe.**

Currently we have the manual consortium plugin [1] as the only implementation in existence that is out there to provide other plugins with a list of nodes and other consortium related metadata. 

What we need is the common interface already implied by the functionality of [1] to be actually be present in a Typescript interface that lives in the `core-api` package so that the implementation of other consortium management plugins can use it as well.

[1] `./packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts`

**Describe the solution you'd like**

1. Define the request/response definitions (just pull the ones currently in the consortium manual  plugin package)
2. Define something like this (again, nothing new here just pulling the existing functionality into a separate interface for re-use by others)
    ```typescript
    import {
      ICactusPlugin,
      GetNodeJwsRequest,
      GetNodeJwsResponse,
      GetConsortiumJwsRequest,
      GetConsortiumJwsResponse,
    } from "@hyperledger/cactus-core-api";
    export interface IPluginConsortium extends ICactusPlugin {

      /**
       * Returns the JSON Web Signature of the consortium metadata, as issued by the
       * **current node** that the request has been issued to.
       * @param req The parameters of the request, if any.
       */
      getNodeJws(req: GetNodeJwsRequest): Promise<GetNodeJwsResponse>;

      /**
       * Returns the JSON Web Signature of the consortium metadata, as issued by
       * **all the nodes in the consortium** that are known to be in the consortium
       * by this current node that the request has been issued to.
       *
       * @param req The parameters of the request, if any.
       */
      getConsortiumJws(req: GetConsortiumJwsRequest): Promise<GetConsortiumJwsResponse>;
    }
    ```

**Describe alternatives you've considered**

Nothing, I'm pretty sure we need to do this because without this other's are blocked from authoring their own consortium plugins which is not what we want.

**Additional context**

N/A

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton

**Comment by jordigiam** [comment]
working on this
