### ISSUE TITLE
feat(ci): provide a common method for automatically testing codes

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#443]
**Is your feature request related to a problem? Please describe.**
There is a need for a common method of automatic code testing in CI environments to maintain code quality in the development of CACTUS. In particular, I propose a code test using Jest since the compatibility between CACTUS's current main language TypeScript/JavaScript and the automated test tool Jest is good.

**Describe the solution you'd like**
Fulfill a common method for automatically testing codes on CACTUS development.

**Comment by petermetz** [comment]
@takeutak Have you seen this?
https://github.com/hyperledger/cactus/issues/238

cc: @sfuji822 @hartm @jonathan-m-hamilton
