### ISSUE TITLE
feat(ledger-plugin): remove the restriction to be npm package for implementing ledger plugins

### ISSUE THREAD

**Issue by sfuji822** [hyperledger/cactus#446]

**Comment by sfuji822** [comment]
Sorry. Can you remove this (duplicated post)? @petermetz

**Comment by petermetz** [comment]
@sfuji822 No worries at all. Best I can do it is close it as a duplicate because I also do not have permission to delete it (Github doesn't allow it).

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/deleting-an-issue

cc: @takeutak @hartm @jonathan-m-hamilton
