### ISSUE TITLE
fix(release-scripts): redundant change log generated

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#459]
**Describe the bug**

I issued the `v0.3.0` release recently and noticed that there are items in the feature list that were already new features in the previous release `v0.2.0` which is not cool of course (as much as I'd like to take credit twice for everything we do).

**To Reproduce**

Issue a release (don't) and observe what I just described above being the case.

**Expected behavior**

Release script should filter down the list of features to only the ones that are new since the previous release (duh).

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`v0.3.0`

**Additional context**

Check this out: https://github.com/hyperledger/cactus/releases/tag/v0.3.0

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton

**Comment by AzaharaC** [comment]
Working on this.

**Comment by petermetz** [comment]
No longer reproducible. Closing it until this happens again.
