### ISSUE TITLE
build(openapi-generator): swap local JDK to container

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#463]
### Description
As a code contributor I want to have to install as little dependencies as possible on my operating system so that it's less of a chore to get on board with the project in general and also I get in trouble less with conflicting versions such as when JDK 8 is needed by one thing and JDK 11+ is the only workable version for some other thing.

As an example the following snippet can be executed to run the OpenAPI generator without actually having JDK on the host system:

```sh
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
    -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
    -g kotlin-spring \
    -o /local/dist/gen/kotlin-spring
```

### Acceptance Criteria
1. JDK is no longer required for building Cactus
2. Relevant documentation has been updated such as `BUILD.md`, `CONTRIBUTING.md` and others.

cc: @sfuji822 @takeutak @hartm @jonathan-m-hamilton

**Comment by sfuji822** [comment]
I hope the solution is implemented as for docker-compose building ready.
That is easy to use and minimizing platform dependency.
