### ISSUE TITLE
refactor(core-api): keychain plugin get/set generic type parameters

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#478]
### Description

https://github.com/hyperledger/cactus/blob/acfa6380c774f6651cf256851ea6c02972474503/packages/cactus-core-api/src/main/typescript/plugin/keychain/i-plugin-keychain.ts

```typescript
  get<T>(key: string): Promise<T>;
  set<T>(key: string, value: T): Promise<void>;
```

Right now we have these methods as generic, but it may be better to lock it down to work on strings only since that's the most common (likely the only?) type we'll be dealing with as the plugin implementations are just passing information between calling code and the keychain backends anyway.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton

**Comment by petermetz** [comment]
cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by twiggins120** [comment]
I'll work on this.
