### ISSUE TITLE
ci: add fuzzer tests for our APIs

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#495]
**Is your feature request related to a problem? Please describe.**

We lack fuzzing tests as a security measure for our web APIs.

**Describe the solution you'd like**

A fully automated solution where the fuzzing runs as part of the CI, but can also be executed locally if needed.
- It should use this project: https://github.com/matusf/openapi-fuzzer
- The documentation should be extended with how to execute the tests locally if needed
- The checks should be part of the CI in a dedicated workflow that runs the containers and then unleashes the fuzzer on them.

**Describe alternatives you've considered**

There's an OpenAPI specific fuzzer out there that we may or may not be able to leverage.

**Additional context**

This came up as part of the CII badge conversations we were having about us trying to hit 100% compliance.

cc: @sfuji822 @takeutak @hartm @jonathan-m-hamilton 

Depends on #1877

**Comment by hristiy4n** [comment]
I would like to take this issue. @petermetz could you assign it to me?

**Comment by petermetz** [comment]
@hristiy4n All yours and thank you very much in advance!

Quick note: The fuzzer is likely to come up with a lot of errors because right now our validation of input parameters is spotty at best. There's already work in progress to add validation in the scope of this: https://github.com/hyperledger/cactus/issues/847

Just saying all this because if we want to make the fuzzer part of the CI suite (which we absolutely should IMO) then there's going to be a dependency to all the fuzzer errors being fixed first prior to us being able to merge this one (since otherwise it would just make all the PRs go red with the CI) 

None of this should stop you from implementing the fuzzing, but I wanted to provide as much information as possible well in advance. :-)

**Comment by hristiy4n** [comment]
Thanks for the heads up @petermetz ! I saw the other issue and I assumed this could happen, but I still think testing is very important and this should be done early and merged when possible :)

**Comment by petermetz** [comment]
> Thanks for the heads up @petermetz ! I saw the other issue and I assumed this could happen, but I still think testing is very important and this should be done early and merged when possible :)

@hristiy4n I could not agree more! Thank you very much! :-)

**Comment by petermetz** [comment]
@hristiy4n Passing this on to someone else from the team, I hope it's okay.
