### ISSUE TITLE
feat: add vs-code dev container json file

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#504]
### Description
As a contributor I want to have convenience when setting up the project for development so that I'm more productive and more likely to actually contribute.

https://code.visualstudio.com/docs/remote/containers
https://code.visualstudio.com/docs/remote/devcontainerjson-reference

### TLDR on dev containers: 

VSCode can build the project inside the dev container so you can spare people the hassle of installing all of the build dependencies of the project on their machine (such as the JDK 8 which many people may run into trouble with especially if they already have a different version installed). With the dev container json file all one would need is VSCode and a functioning docker installation to be able work on Cactus code. @kikoncuo 

### Acceptance Criteria
1. .devcontainer.json file added in the project root
2. The image references by the added `.devcontainer.json` file in step 1) suports Docker in Docker or at least binding to the host's docker so that integration tests can be executed inside the container which themselves start other containers for ledger simulation.
3. Documentation added in the README.md that mentions the fact that we have this convenience feature available for those who do not wish to pollute their host machine with NodeJS/JDK installations for example.

cc: @sfuji822 @takeutak @hartm @jonathan-m-hamilton

**Comment by TonyRowntree** [comment]
I am taking this

**Comment by TonyRowntree** [comment]
**Additional Acceptance Criteria:**

- Find out if it is possible to create more than one devcontainer within the project and then discuss what folders a devcontainer may be useful for

**Comment by petermetz** [comment]
@TonyRowntree Random, potentially helpful fact: If you hit issues with docker containers needing to run inside the dev-container I recommend [mounting the sock file of the host](https://devopscube.com/run-docker-in-docker/#method-1-docker-in-docker-using-var-run-docker-sock) machine's docker daemon instead of going the full-on [docker-in-docker](https://hub.docker.com/_/docker) route.

Might not even need this, but in case you do I figured I'd jot it down.
