### ISSUE TITLE
feat(besu): erc-20 HTLC

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#513]
**Is your feature request related to a problem? Please describe.**

We need a Cactus plugin for executing atomic swaps via HTLCs for ERC-20 tokens There's a separate task for ETH tokens that is otherwise the same task as this.

**Describe the solution you'd like**

Some inspiration could be taken from [this](https://github.com/jelly-swap/jelly-erc20-htlc), but the solidity code itself is just the tip of the ice-berg since we have to work within the plugin architecture and work out other bells and whistles such as contract deployment so that the overall experience for a developer using Cactus as a framework is pleasant rather than overwhelming.

There's a lot more information in the parent issue where the common theme is set for all these sub-tasks related to HTLC development for Cactus.

On a high level the solution should consist of 
1. the solidity code and the boilerplate to make that solidity code callable via the Cactus API clients:
2. The plugin package under `./packages/cactus-plugin-htlc-eth-besu` (naming things is a difficult problem, feel free to suggest better names)
3. OpenAPI spec json file (in the plugin package)
4. Generated API client in Typescrit (based on the OpenAPI spec)
5. The plugin has to be able to deploy the solidity code to the underlying ledger (solidity code to be embedded as a JSON resource, see parent issue for explanation)

**Describe alternatives you've considered**

`N/A`

**Additional context**

Parent: feat(core-api): atomic swaps with HTLCs #510
Sibling: feat(besu): eth HTLC #512

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton

**Comment by RafaelAPB** [comment]
@petermetz this is a great idea and very relevant - with Cactus, the deployment and management of instances of HTLCs could be automized. I would say this constitutes a business logic plugin because it implements well-defined logic using a connector/validator pair (Besu). Now,  this poses a problem in terms of organization: will we see the number of packages escalate indefinitely? Are we accounting for "core" business logic plugins, that should be separated from the rest? This is probably good material for being discussed in the next meeting.

**Comment by petermetz** [comment]
> @petermetz this is a great idea and very relevant - with Cactus, the deployment and management of instances of HTLCs could be automized. 

@RafaelAPB Thank you very much! :-) 

> I would say this constitutes a business logic plugin because it implements well-defined logic using a connector/validator pair (Besu).

My take (and I'm willing to be wrong here as usual): It is closer to BLPs than let's say the connector plugins (which are clearly not BLPs) but still, one has to ask, if the HTLC plugin is a BLP, then what is the exact business use case it's implementing? And my answer to that is that there is none because it's still more of a core/generic plugin, a lower level primitive that can be used by BLPs but do not itself carry any business logic.

> Now, this poses a problem in terms of organization: will we see the number of packages escalate indefinitely? 

My hunch is that the number of plugins will be a function of the number of ledgers supported which (hopefully) will continue to increase indefinitely, yes, but as DLTs mature, maybe we'll reach a stable equilibrium, regarding this I'm definitely just guessing. 

I have given this (specifically the plugin count) some thought in the past and concluded that eventually we'll have to start storing plugin packages in dedicated git repositories to be able to scale. A case study I can offer where this strategy was successful is the ansible project where they broke out the main repo into smaller repos (and the reason they could do it is because they also have a plugin architecture in place).
Their justification there was that at any given time there would be 2 *thousand* open bugs on the GH issue tracker regardless of how much effort was spent on closing them, the newly added plugins and their related issues were just growing quicker than they could close the old ones. I'm looking forward to us having that problem one day and I think we'll be in a good position to fix it as well (and maybe we don't wait until things get that bad but instead keep it steady with a gradual unloading of plugins to their own repos/maintainers).  

> Are we accounting for "core" business logic plugins, that should be separated from the rest? This is probably good material for being discussed in the next meeting.

May have partially commented on this above as well, but wanted to add an additional thought here and in the upcoming meeting! 

I think the optimal recipe to decide how many/which plugins to put in their own repos is to let the community drive these decisions.
Example 1: If there's not much interest from people in being maintainers for certain plugins then we should either keep those in the main cactus repo or just straight up deprecate them if they are not really used by anyone.
Example 2: If there's 100 plugins and there are people willing to maintain some of those in separate repos, then we could break those out so that issue management/PR reviews can become easier. I also want to note here though that streamlined processes could be created with the labeling system that ensures that things go smoothly even if we reached critical mass.

**Comment by jordigiam** [comment]
I'm working on this, I'm currently generating end-to-end test
