### ISSUE TITLE
Gateway-based interoperability: ODAP support

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cactus#517]
One of the main adoption drivers of Cactus will be the flexibility of the framework, including the support of blockchain interoperability standards.
At the Internet Engineering Task Force, work is being conducted on defining a digital asset protocol that can be used by enterprises - ODAP. 

Protocol description
https://www.ietf.org/archive/id/draft-hargreaves-odap-01.txt

Resiliency for ODAP
https://datatracker.ietf.org/doc/draft-belchior-gateway-recovery/

If ODAP evolves to a standard, enterprises can use it to communicate with the blockchains of other enterprises. Enterprises can then leverage Cactus' connectors and validators, supporting ODAP as a business logic plugin.

**Describe the solution you'd like**
ODAP-gateway implementation as a BLP

**Describe alternatives you've considered**
Other alternatives are ad-hoc communication protocols. Cactus will need to support standard protocols for communication across ledgers.

**Comment by RafaelAPB** [comment]
@petermetz I can work on this issue

**Comment by petermetz** [comment]
> @petermetz I can work on this issue

@RafaelAPB Cheers, I assigned it under your name. Repeating my rocket chat message here: let me know if there's anything specific I can help out with either here or on RC/email/etc.!

**Comment by RafaelAPB** [comment]
We could add this feature to release v1 or v2 @petermetz

**Comment by petermetz** [comment]
@RafaelAPB Done. Thank you very much for the help!

**Comment by RafaelAPB** [comment]
@jscode017 feel free to close this issue when the PR is merged :)

**Comment by RafaelAPB** [comment]
Resolved by PR #1275

**Comment by RafaelAPB** [comment]
Enhanced by #1902
