### ISSUE TITLE
fix(connector-besu): missing value when sending transactions

### ISSUE THREAD

**Issue by kikoncuo** [hyperledger/cactus#549]
**Describe the bug**

When sending a transaction with ether an extra value is required in the transaction encoding which is missing

**To Reproduce**

Try to call a payable smart contract function, it will fail because ether can't be specified in the correct position

**Expected behavior**

Ether can be sent when sending ether transactions

**Logs/Stack traces**

pending...

**Screenshots**

pending...

**Hyperledger Cactus Plugins/Connectors Used**

 - Besu connector

**Additional context**

https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#id84

IE:
```
web3.eth.sendTransaction({
    from: '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe',
    to: '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe',
    value: '1000000000000000'
})
```

**Comment by jordigiam** [comment]
Working on this

**Comment by petermetz** [comment]
https://github.com/hyperledger/cactus/blob/main/packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json#L451

**Comment by kikoncuo** [comment]
https://github.com/hyperledger/cactus/pull/554#issue-568497729

PR done and merged
