### ISSUE TITLE
docs(readme.md): fix project name, link to sub-docs

### ISSUE THREAD

**Issue by kikoncuo** [hyperledger/cactus#551]
**Is your feature request related to a problem? Please describe.**
As a developer reading about Cactus, right now, the readme.md is my main landing page, it contains references to the old project name, and it's not linking to the new markdown documentation that's being generated

**Describe the solution you'd like**
Update the main readme

**Describe alternatives you've considered**
Updating our readthedocs directly, but since we are going to automatically pull the information for the markdowns it makes more sense to keep those up to date

**Acceptance criteria**
- [x] Delete old references
- [x] Improve pointers to other markdown doc files

**Comment by AzaharaC** [comment]
working on this.

**Comment by AzaharaC** [comment]
References to other documents are correct.
