### ISSUE TITLE
chore(deps): upgrade to openapi generator 2.2.6

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#584]
There's been some flickering with the generated files recently because we slipped up with one of the PRs (I think) where the 5.0.0 generator was used by accident.
Would've been better to keep with the exact version from before, BUT that said version is actually a beta one so there is a case to be made for pulling the plug on an upgrade which isn't really a disruptive change, but it will generate a large diff for sure.

Edit: 2.2.6 is the latest version of this tool.

**Comment by travis-payne** [comment]
This will be addressed by issue #763
