### ISSUE TITLE
refactor(connector-besu) connector refactor, consolidate transaction invocation API

### ISSUE THREAD

**Issue by kikoncuo** [hyperledger/cactus#609]
Parent: feat(cactus): Standardized common interface functionality transaction across connectors #604

Description:
Update the spec for Besu to meet the standard as defined in the parent issue.

Acceptance criteria:
* OpenAPI spec meets definition as specified in the parent
* Update existing references (Demo site, tests, HTLCs)
* All tests passing

depends on #612
depends on #613

**Comment by AzaharaC** [comment]
working on this
