### ISSUE TITLE
feat(connector-Besu) Load contract instances from compiled contract files

### ISSUE THREAD

**Issue by kikoncuo** [hyperledger/cactus#612]
Parent: feat(cactus): Standardized common interface functionality transaction across connectors #604
This is a dependency for #609

Description:
Using the .json files generated from compiling a Solidity smart contract, the Besu/Quorum connector plugin should be able to load web3 smart contract instances in the constructors, write them using the keystore plugin, store them in a map and use them to generate the transactions simplifying the usage vs providing the abi in a per transaction basis.

Acceptance criteria:
* Contracts are loaded from a folder and invokable by using their contract name.

**Comment by jordigiam** [comment]
Working this

**Comment by AzaharaC** [comment]
Working on this.

**Comment by AzaharaC** [comment]
To solve this task, we need to modify the deploy function to update the networks field in the compiled contract .json file, like other SDKs do (https://trufflesuite.github.io/artifact-updates/requirements/truffle.html). This is necessary to recover the contract instance deployed on the blockchain from the compiled contract file.
