### ISSUE TITLE
feat(connector-fabric) Create signing credentials for Fabric

### ISSUE THREAD

**Issue by kikoncuo** [hyperledger/cactus#614]
Parent: feat(cactus): Standardized common interface functionality transaction across connectors #604

Description:
Currently the Fabric connector doesn't use a signingCredential like the Besu and Quorum connectors. The signingCredential offers an abstraction layer to key management and improves interface compatibility when using Cactus.

Acceptance criteria:
* A signingCredential for Fabric is created
* Existing references are updated to use it (Demo site, tests, HTLCs)
* All tests passing

**Comment by AzaharaC** [comment]
Working on this
