### ISSUE TITLE
feat(VerifierFactory): add connection feature to both of socket.io-type Validator and http-type Validator

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#639]
**Is your feature request related to a problem? Please describe.**
The current version of Verifier can only communicate with socket.io types of Validators implemented in Cactus.

**Describe the solution you'd like**
To implement VerifierFactory functionality to make Verifier communicate with both socket.io and http Validators

**Comment by petermetz** [comment]
@takeutak Was this resolved by the PR linked?
