### ISSUE TITLE
fix(examples): add explanations about the port number to examples/electricity-trade and examples/cartrade

### ISSUE THREAD

**Issue by fumiya-kobayashi** [hyperledger/cactus#668]
**Describe the bug**

However modifying the port number is an optional procedure in examples/electricity-trade and examples/cartrade, the current README on examples/electricity-trade and examples/cartrade does not mention it.

**Expected behavior**

Modifying README on the above point.

**Comment by petermetz** [comment]
@fumiya-kobayashi Can this issue be closed now that the linked PR has been merged?

**Comment by fumiya-kobayashi** [comment]
> @fumiya-kobayashi Can this issue be closed now that the linked PR has been merged?

Thank you for letting me know.
I'd close this.
