### ISSUE TITLE
feat(keychain-vault): Fixing the incomplete endpoint methods

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cactus#676]
### Description
As a developer, I want to fix the following methods, enable them in installWebServices() method and fix the skipped test cases for the same
GetKeychainEntryEndpointV1
SetKeychainEntryEndpointV1

These files specifically 
packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/set-keychain-entry-endpoint-v1.ts (getExpressRequestHandler method)
packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/get-keychain-entry-endpoint-v1.ts (getExpressRequestHandler method)
packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault.ts (installWebServices method)
packages/cactus-plugin-keychain-vault/src/test/typescript/integration/plugin-keychain-vault.test.ts (skipped test cases)

### Acceptance Criteria
1. The above endpoint methods should have the methods fixed.
2. The skipped test cases should be working

**Comment by petermetz** [comment]
@jagpreetsinghsasan Was the linked PR also resolving this issue or is there more to this one that still needs work? Just double checking if we should close the issue or not.
