### ISSUE TITLE
feat(test-tooling): containers#pruneDockerResources() observability

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#694]
### Description
As a contributor I want to have a way to see what is the outcome of the docker resources pruning so that it is easier for me to debug infrastructure/hardware related CI failures that I encounter.

A good example of such issue is when the GitHub CI Action started failing because the disk was full with docker images that we created in the test cases.
It is particularly hard to debug these failures because the test runner will show a particular test failing and that failure of that test case will not be reproducible on any other machine unless that machine also has the disk full issue.

### Acceptance Criteria
1. The pruning method can log it's own results for itself via a log level parameter
2. The pruning method also returns the outcome of the pruning process so that callers can either log that for themselves or pass it further up to their callers when applicable.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @jagpreetsinghsasan

**Comment by kikoncuo** [comment]
Is this for local tests or github's?
