### ISSUE TITLE
Cartrade example project - transaction is not being processed, channel, and chaincode does not exist

### ISSUE THREAD

**Issue by brsbalazs** [hyperledger/cactus#705]
I have been tried starting the Cartrade example project, and followed the instruction in the readme one by one, but after both component has been initialized and i tried to create a transaction, noticed error messages in the log of the Fabric network telling that, the channel called mychannel does not exist, the transaction could not be processed. An error message also appears when execute the script-get-app.sh, states that the chaincode fabcar not found.

2021-03-22T19:52:27.864Z - warn: [Query]: evaluate: Query ID "[object Object]" of peer "peer0.org1.example.com" failed: message=make sure the chaincode fabcar has been successfully instantiated and try again: chaincode fabcar not found, stack=Error: make sure the chaincode fabcar has been successfully instantiated and try again: chaincode fabcar not found

**Comment by petermetz** [comment]
@takeutak @sfuji822

**Comment by takeutak** [comment]
Thank you for trying cartrade app.
The error indicates that the fabric ledger is not properly started in the README Boot process. Could you tell me about the following two points?

(1) Could you start script-start-ledgers.sh in the Boot method? If fabric containers are launched with docker ps, it is OK.

(2) Did you complete the Boot method? If you haven't done the Boot method, running "How to use this application" won't work.

**Comment by takeutak** [comment]
@brsbalazs cc: @petermetz @sfuji822 

I'm sorry to trouble you, again.
I have also looked into the errors you mentioned, and it appears that there was a change in the procedure for installing fabric-samples in Hyperledger fabric. If the third argument is not found in the following procedure, an error occurs. Previous Cactus code used only the second argument, which caused errors.

curl -sSL http://bit.ly/2ysbOFE | bash -s -- <fabric_version> <fabric-ca_version> <thirdparty_version>
(c.f.) https://hyperledger-fabric.readthedocs.io/en/release-1.4/install.html

I posted a pull-request including codes for correcting about the above point. This PR is going to be merged into the main branch soon.
So, could you try the procedure again after the above merge? I will comment on this issue when the code merges again.

**Comment by brsbalazs** [comment]
@takeutak 

Thanks for the quick fix, I am going to give it a try again after the pr has been merged.

**Comment by takeutak** [comment]
@brsbalazs 
Thank you for waiting! Sorry for my late reply.
The above code has been merged, so could you download the code from the commit below and try it out? This code will be released as V 0.4.1 at a later date.
 - **Code**: https://github.com/hyperledger/cactus/tree/a93e4511ca05dc242697e4bc91618318f9d4e85d

The manual to use the sample applications "car-trade" and "electricity-trade" is the following:
 - **car-trade**: https://github.com/hyperledger/cactus/blob/a93e4511ca05dc242697e4bc91618318f9d4e85d/examples/cartrade/README.md
 - **electricity-trade**: https://github.com/hyperledger/cactus/blob/a93e4511ca05dc242697e4bc91618318f9d4e85d/examples/electricity-trade/README.md

Please let me know if you don't know how to use it or it doesn't work well.

**Comment by brsbalazs** [comment]
@takeutak 
Works fine, the transactions are being processed properly. Thanks for the fix. 
I am closing the issue.

**Comment by takeutak** [comment]
@brsbalazs Good job for working the code well.
The version 0.4.1 has been released, so the same business-logic examples can be executed using this.
https://github.com/hyperledger/cactus/tree/v0.4.1
