### ISSUE TITLE
feat(LedgerPlugin): add TransactionSigner on LedgerPlugin

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#708]
**Is your feature request related to a problem? Please describe.**
In the current Cactus, the signature function is implemented for each BLP-example-apps. However, originally, the signature function can be shared by ledgers. This reduces the burden on the implementer of BLP-example-apps.

**Describe the solution you'd like**
To separate the signature functionality into TransactionSigner under LedgerPlugin

**Comment by petermetz** [comment]
@takeutak Can this be closed now that the linked PR has been merged?
