### ISSUE TITLE
feat(ci): support debugging on CI server through ssh

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#717]
### Description
As a contributor I want to be able to debug the failing tests on the CI server directly so that I can figure out what is going wrong even if my tests are only failing on the CI server and not on my local machine (which is a very common scenario at present...)

Use this (?) => https://github.com/marketplace/actions/debugging-with-ssh

### Acceptance Criteria
1. Works out of the box with VSCode debugger (preferably, but other is acceptable too)
2. GIF tutorial in CONTRIBUTING.md showing exactly how it's done in 30 seconds or less.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @jagpreetsinghsasan

**Comment by Leeyoungone** [comment]
Hello! May I take up this issue? I'd like to give this a try ⭐ !

**Comment by petermetz** [comment]
@Leeyoungone All yours! :-)
Disclaimer: I tested out a few months back and the linked GH workflow does indeed work for the purpose of providing SSH access to the CI, but I haven't had a chance to try out if I could debug tests as well so that's the interesting bit and if you  can make it work great, if not, then it's okay to  break this into two parts one is about documenting how to use the SSH connection itself and then a second issue (to be completed at a later time) about the specific VSCode debugging.
