### ISSUE TITLE
fix(examples): add explanations about docker group to examples/electricity-trade and examples/cartrade

### ISSUE THREAD

**Issue by Ryu-Shinzaki** [hyperledger/cactus#724]
**Describe the bug**
The user account must belong to the docker group when you run script-ledger-start.sh, but the current README 
on examples/electricity-trade and examples/cartrade has not enough explanations.

**Expected behavior**
To modify README on the above point

**Comment by takeutak** [comment]
Thank you for pointing it out! You said you would modify electricity-trade/README, so could you please issue a pull-request about this point?

**Comment by petermetz** [comment]
@Ryu-Shinzaki Can this issue be closed now that the linked PR has been merged?

**Comment by Ryu-Shinzaki** [comment]
> @Ryu-Shinzaki Can this issue be closed now that the linked PR has been merged?

Thank you for the notice.
I'll close this issue.
