### ISSUE TITLE
feat(verifier): adapt Verifier to http-typed events

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#735]
**Is your feature request related to a problem? Please describe.**
The current verifier on Cactus Node Server cannot deal with http-typed ledger-events when cactus connects with http-typed validators.

**Describe the solution you'd like**
@takeutak will provide a proto code to solve the above issue soon.

**Comment by petermetz** [comment]
@takeutak Can this issue be closed now that the PR linked has been merged?
