### ISSUE TITLE
fix(whitepaper): fix cactus_arch.svg

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#737]
**Describe the bug**

The current Cactus architecture diagram (cactus_arch.svg on whitepaper) has a typo. Also, when you apply the black background setting on GitHub, the diagram does not display correctly.

**To Reproduce**

To post a pull-request for solving this issue.

**Comment by petermetz** [comment]
@takeutak Can this issue be closed now that the PR has been merged?
