### ISSUE TITLE
refactor(examples): add the abstracts of examples/car-trade and examples/electricity-trade

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#740]
**Is your feature request related to a problem? Please describe.**
The current examples/cartrade and examples/electricity-trade don't have an enough explanation about the abstracts of these examples.  This is unkind to first-time users.

**Describe the solution you'd like**
To add such an explanation on the READMEs on these examples.

**Comment by petermetz** [comment]
@takeutak Can this be closed now that the PR linked has been merged?
