### ISSUE TITLE
fix(connector-corda): container image kotlin compilation fails in model

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#763]
**Describe the bug**

The corda connector jvm backend's container image build is failing on DockerHub due to a compilation error in the generated model code.
This is likely related to the recent downgrade to the standard version of the openapi generator (from 5.0.0 to 5.0.0-beta2).

**To Reproduce**

Build the container image on DockerHub or locally and observe it failing.

**Expected behavior**

Build does not fail.

**Logs/Stack traces**

```sh
Step 5/24 : RUN gradle build
---> Running in f1dbb3aad89c
Welcome to Gradle 6.8!
Here are the highlights of this release:
- Faster Kotlin DSL script compilation
- Vendor selection for Java toolchains
- Convenient execution of tasks in composite builds
- Consistent dependency resolution
For more details see https://docs.gradle.org/6.8/release-notes.html
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileKotlin
[91me: /kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/JarFile.kt: (29, 5): This type has a constructor, and thus must be initialized here
[0m
> Task :compileKotlin
FAILED
[91m
[0m
[91mFAILURE: [0m
[91mBuild failed with an exception.[0m
[91m
[0m
[91m
[0m
[91m* What went wrong:[0m
[91m
[0m
[91mExecution failed for task ':compileKotlin'.
[0m
[91m> Compilation error. See log for more details[0m
[91m
[0m
[91m
[0m
[91m* Try:
[0m
[91mRun with --stacktrace[0m
[91m option to get the stack trace. Run with --info or [0m
[91m--debug option to get more log output. Run with [0m
[91m--scan to get full insights.[0m
[91m
[0m
[91m
* Get more help at [0m
[91mhttps://help.gradle.org
[0m
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
[91m
[0m
[91mBUILD FAILED in 3m 41s
[0m
1 actionable task: 1 executed
Removing intermediate container f1dbb3aad89c
The command '/bin/sh -c gradle build' returned a non-zero code: 1
```

**Screenshots**

`N/A`

**Cloud provider or hardware configuration:**

`N/A`

**Operating system name, version, build:**

`N/A`

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`0.4.0`

**Hyperledger Cactus Plugins/Connectors Used**

Corda

**Additional context**

There's another issue open with globally upgrading the openapi generator to 5.0.0 so that would likely solve this bug as well implicitly.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @jagpreetsinghsasan

**Comment by travis-payne** [comment]
I'll be having a look at this!
