### ISSUE TITLE
docs(examples): supply chain image boot goes silent for 10 minutes

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#780]
**Describe the bug**

The container appears as if it hung because it takes a long time to download the AIO images and it's not saying anything in the logs for that period of time.

**To Reproduce**

Launch the example container as instructed by the readme and watch how it appears to hang for about 10 minutes while it is actually hard at work setting everything up.

**Expected behavior**

Logs should show a little more liveness so people don't abandon the example assuming that it's broken.

The demo has an adequate amount of documentation around what conditions, exactly, it needs to work.

**Logs/Stack traces**

N/A

**Screenshots**

N/A

**Cloud provider or hardware configuration:**

Dev machine

**Operating system name, version, build:**

N/A

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`main` @ 0.4.1

**Hyperledger Cactus Plugins/Connectors Used**

N/A

**Additional context**

N/A

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @jagpreetsinghsasan

**Comment by hartm** [comment]
I'm not sure this counts as a bug, but it would be a nice QoL fix.  Thanks Peter!

**Comment by hartm** [comment]
Another thing:  more documentation around what conditions, exactly, the demo needs to work would be great.  This probably isn't the place to say this, but in the long run, a demo that business people could easily run on standard windows corporate laptops would be great.
