### ISSUE TITLE
 Refactor data-check for protocol implementation 

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger/cactus#8]
**Problem statement**  
Users and developers should be able to implement their own validator's verification logic and the code structure should reflect this capability  

**Current state**  
"Data-check" logic is located under the Validator class as a standalone function and implement only the "existence" verification  

**Desired state** 
"Data-check" logic is located under the connector section and is part of the plugin (different integration for each platform). Verification logic and how to build your own figures in the documentation  

Todo    

- [ ] Move the data-check function and the verification components to the plugin section   
- [ ] Implement a more generic verification scheme to help new developers implement their own functions   
- [ ] Document the importance of the validator's verification logic and how to modify it to match specific use cases

**Comment by petermetz** [comment]
Fixed by #123 => users can now implement entirely custom validation logic through the plugin architecture
