### ISSUE TITLE
test(ci): should fail if git index not empty after successful build

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#809]
### Description
As a developer I don't want to have random files changing/being added to my git index after building the project for the first time so that I'm not confused about what those changes are.

Example: I check out the project and then build it, all good, except that some package lock files have changed and I don't know why, don't know if I should commit those or not, etc...

### Acceptance Criteria
1. ci.sh throws a tantrum if it ran npm run configure and then it found the git index not to be empty.
2. ci.sh throws a tantrum if it ran *everything* successfully and then it found the git index not to be empty.
3. There two points where the git index is checed (see above) - one for speed, e.g. early detection, two for being absolutely sure that the build does not produce version controlled changes.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @jagpreetsinghsasan @arnab-roy

**Comment by hristiy4n** [comment]
I would like to take this issue. Could you clarify what the expected behavior should be when detecting changes? Should ci.sh output a message to stderr and exit with 1 or just output a message with a hint why the files have been changed?

**Comment by petermetz** [comment]
@hristiy4n Awesome, all yours! If you need help with anything/need more details, etc. then just ping me either here, on rocket chat, on the mailing list or come hang out at one of our pair programming calls that you can find on the [Hyperledger Calendar](https://lists.hyperledger.org/groups).

**Comment by hristiy4n** [comment]
@petermetz Thanks for the swift response! I have addressed the issue in PR https://github.com/hyperledger/cactus/pull/864

**Comment by petermetz** [comment]
@hristiy4n Awesome, thank you for the contribution! I approved the PR just now.
