### ISSUE TITLE
docs(readthedocs): publish ledger support matrix for connectors

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#886]
### Description
As someone evaluating Cactus to be used on a project of mine I want to be able to quickly figure out if the ledger versions that are supported by Cactus so that I can have confidence that looking further into the framework won't be a waste of my time in case it turns out not to support my ledger of choice.

This would be a dedicated page on the left hand side of the ReadTheDocs page (and also it's own markdown file within the `./docs` directory.
The other reason why I want us to have this is to be able to showcase that we do support the latest and greatest wherever possible.

### Acceptance Criteria
1. Information is accessible via the top level navigation pane of the ReadTheDocs site
2. A complete matrix is included that covers all the versions of all the supported ledgers on a level of minor versions (such as 4.5, 4.6, 4.7 etc for Corda for example.
3. Links are provided to **actual test cases** verifying that said version is indeed working as intended. This is important because it will force us to add the tests prior to making claims about support and once the tests are in place we'll have back-testing mostly for free (we'll have more tests to maintain of course, but that's as easy as we can make it on ourselves).
4. The matrices should include the different Cactus versions as well so that if I'm on an older version of Cactus I can still quickly figure out what are my options there if I don't want to upgrade Cactus to the latest and greatest due to whatever reason. We can have v0.4 as the first release then 0.5, 0.6, etc.
5. The matrices should also expand on an additional dimensions of different operations of the connectors being compatible with different versions of the ledgers. For example the Fabric connector could run transactions against a Fabric 2.x ledger since `0.3.0` but contract deployment is only coming in `0.5.0` so this information also needs to be made clear in the documents.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy

**Comment by elenaizaguirre** [comment]
Working on this
