### ISSUE TITLE
Enhance Credential Storage

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger/cactus#9]
Write a plugin that uses encryption at rest through some stable piece of software such as `Vault` or one of the cloud providers own key/secret management solutions (or both, actually).

**Comment by petermetz** [comment]
This was resolved as a happy side effect of https://github.com/hyperledger/cactus/pull/475 since that PR also added support for our first real keychain backend that actually supports encryption at rest (Vault).
