### ISSUE TITLE
feat(keychain-aws-secretmanager): create aws secret manager plugin

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cactus#912]
### Description
As a developer, I want to create a plugin for aws secret manager and perform tasks related to secret management like createSecret and retrieveSecret sort of functionalities.

For reference,
https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html

### Acceptance Criteria
1. New package to be created as `@hyperledger/cactus-plugin-keychain-aws-sm`
2. Plugin must implement the central keychain plugin Typescript interface we have in the core-api package
3. End to end tests to be written that verify that the plugin does indeed work by leveraging localstack
4. In a separate PR to this add a helper class in the test-tooling package called `LocalstackTestContainer` which launches a localstack container
5. Make sure to have the healthcheck of the local stack container passing as part of the start() method's return value (the promise should only resolve once the container is healthy and the localstack services are up and running,  ready to serve requests)
6. The helper class to have methods to expose the credentials, port numbers, etc. that are required to configure/instantiate the `PluginKeychainAwsSm` class which is to be implemented as part of the package from point 1)

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz  @arnab-roy

**Comment by jagpreetsinghsasan** [comment]
@petermetz what should be the possible acceptance criteria?

**Comment by petermetz** [comment]
> @petermetz what should be the possible acceptance criteria?

@jagpreetsinghsasan Updated the issue description with it.
