### ISSUE TITLE
feat(keychain-aws-sm): complete request handler and endpoints 

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cactus#967]
### Description
As a developer, I want to complete the code to enable the endpoints
get-keychain-entry
set-keychain-entry
delete-keychain-entry (or maybe use set-keychain-entry with tags for deletion)
Also, write tests that use the API client instead of the plugin instance directly.

### Acceptance Criteria
1. Update openapi.json at packages/cactus-plugin-keychain-aws-sm/src/main/json/openapi.json
2. Update the endpoints at packages/cactus-plugin-keychain-aws-sm/src/main/typescript/webservices
3. Update the remote adapter code at packages/cactus-plugin-keychain-aws-sm/src/main/typescript/plugin-keychain-aws-sm-remote-adapter.ts
4. Update the test code at packages/cactus-plugin-keychain-aws-sm/src/test/typescript/integration/plugin-keychain-aws-sm.test.ts

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy @petermetz  @TonyRowntree @travis-payne

**Comment by petermetz** [comment]
cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

**Comment by Leeyoungone** [comment]
I'll work on this ! @petermetz

**Comment by ty-lazar** [comment]
@petermetz Same issue as #1010 - the keychain-aws-sm package doesn't exist

**Comment by petermetz** [comment]
> @petermetz Same issue as #1010 - the keychain-aws-sm package doesn't exist

@ty-lazar @Leeyoungone Please base the feature branch off of Jagpreet's branch (there's an open PR with it)
