### ISSUE TITLE
feat(keychain-aws-sm): bootstrap README.md

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/cactus#968]
### Description
As a developer, I want to update the README.md describing the plugin and examples for its usage.

### Acceptance Criteria
1. README.md present at packages/cactus-plugin-keychain-aws-sm/README.md should be updated with the plugin description and example usage.

**Comment by jagpreetsinghsasan** [comment]
@petermetz I have started working on this in the meanwhile.

**Comment by petermetz** [comment]
> @petermetz I have started working on this in the meanwhile.

@jagpreetsinghsasan Great, thanks for being proactive ;-)
