### ISSUE TITLE
build: migrate to GitHub Container Registry when it hits GA

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#995]
### Description
As a maintainer I want to have automated checks stopping PRs which break the container image builds so that I don't unknowingly introduce bugs to the codebase when accepting a PR that looks okay but it's not. 

> Note: The Container registry is currently in public beta and subject to change. During the beta, storage and bandwidth are free. To use the Container registry, you must enable the feature preview. For more information, see "Introduction to GitHub Packages" and "Enabling improved container support with the Container registry."

Source: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

#### Why though?

Because Docker Hub (Docker Cloud) can only observe branches but not PRs (when the branch is not in the repo but on a fork)

### Acceptance Criteria
1. It is impossible to merge a pull request if it breaks any of the container images that we have
2. The checks are integrated into the standard PR process meaning that they show up as failing on the PR itself, there's no need to check any other places, it's all there on the bottom section of the PR page
3. All container images are covered that we have (this means that the existing bugs have to be fixed - we have some broken container image builds exactly because these checks are not in place at present so bugs in the Dockerfile's snuck in)

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy @ryjones

**Comment by ryjones** [comment]
This action builds and publishes to GHCR for every step
https://github.com/hyperledger/ursa-wrapper-go/blob/main/.github/workflows/build.yaml

This action creates a release based on a tag
https://github.com/hyperledger/ursa-wrapper-go/blob/main/.github/workflows/release.yaml

**Comment by petermetz** [comment]
Once we have a fix for this, it might also implicitly fix this one: https://github.com/hyperledger/cactus/issues/1567
